SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO


CREATE PROCEDURE [apietl].[sp_Load_IMC_Prodcopy_MasterDB]
AS
    MERGE ods.IMC_ProductionCopy_MasterDB AS TARGET
    USING
        ( SELECT    *
          FROM      ( SELECT    RECIPIENT_ID ,
                                Email ,
                                [Opt In Date] ,
                                [Opted Out] ,
                                [Opt In Details] ,
                                [Email Type] ,
                                [Opted Out Date] ,
                                [Opt Out Details] ,
                                [2016 PSL Payment Paid] ,
                                [2017 PSL Amount Due] ,
                                [2017 PSL Payment Paid] ,
                                [21 or older] ,
                                [AF Season Schedule] ,
                                [AF Ticket Offers] ,
                                AUExclusiveContentNotifications ,
                                AUInTheStadiumNotifications ,
                                AUMatchStartNotifications ,
                                AUParkingAndTransitNotifications ,
                                AUScoringNotifications ,
                                AUTeamNewsNotifications ,
                                [Academy Team] ,
                                [Academy Tried Out] ,
                                [Additional Comments] ,
                                Address1_City ,
                                Address1_Country ,
                                Address1_County ,
                                Address1_Line1 ,
                                Address1_Line2 ,
                                Address1_Line3 ,
                                Address1_PostalCode ,
                                Address1_StateOrProvince ,
                                [Agree Official Rules] ,
                                AllowSMS ,
                                [Appointment Time] ,
                                AssistantName ,
                                AssistantPhone ,
                                [Associated Archtics ID Suite Owner Admin] ,
                                BirthDate ,
                                CRM_Contact_ID ,
                                Company ,
                                [Corporate Client or Employee Entertainment] ,
                                [Corporate Entertainment] ,
                                [Current Stadium Employee] ,
                                DoNotBulkEMail ,
                                DoNotBulkPostalMail ,
                                DoNotEMail ,
                                DoNotPostalMail ,
                                [Executive Member] ,
                                [Falcons Group] ,
                                [Falcons Home Opponents] ,
                                [Falcons Insider] ,
                                [Falcons SGB TE TF] ,
                                [Falcons Season Ticket Holder] ,
                                [Falcons Season Tix Due] ,
                                [Falcons Seating Preference] ,
                                FirstName ,
                                [Founding Members no seats] ,
                                [Founding Members with seats] ,
                                FullName ,
                                [GA Dome Premium Events] ,
                                [GA Dome Seating Preferences] ,
                                GenderCode ,
                                [Group Size] ,
                                [Group Type] ,
                                HasChildrenCode ,
                                JobTitle ,
                                [KIA Account] ,
                                KORE_Type ,
                                LastName ,
                                Last_Click ,
                                Last_Open ,
                                Last_Sent ,
                                [MBS Hiring Emails] ,
                                [MBS Seating Interest] ,
                                MiddleName ,
                                [Mobile User Id] ,
                                MobilePhone ,
                                [My Finder] ,
                                [Opt Out of Arthur M Blank Foundation Email Communication] ,
                                [Opt Out of Atlanta Falcons Email Communication] ,
                                [Opt Out of Atlanta United Email Communication] ,
                                [PSL Owner] ,
                                [Part Time Positions] ,
                                [Phone Call Opt In] ,
                                [Playoff Payment] ,
                                [Preferred Partner] ,
                                [Preferred Ticket Price] ,
                                PreferredLanguage ,
                                [Primary Rep] ,
                                [Primary Rep Email] ,
                                [Primary Rep Name] ,
                                [Primary Rep Phone] ,
                                [Question or Comment] ,
                                Salutation ,
                                [Seating Level Preference] ,
                                [Send Hour] ,
                                StateCode ,
                                Suffix ,
                                [Team Member Referral] ,
                                [Team Member Requirements] ,
                                Telephone1 ,
                                Telephone2 ,
                                [UTD Acct Number] ,
                                [UTD Event Sign Up] ,
                                [UTD Group] ,
                                [UTD Group  Type] ,
                                [UTD Group Size] ,
                                [UTD Home Opponents] ,
                                [UTD Multi Game] ,
                                [UTD SGB TE TF] ,
                                [UTD Season Schedule] ,
                                [UTD Season Tix Due] ,
                                [UTD Seating Preferences] ,
                                [UTD Test_Behavior] ,
                                [UTD Test_Rank] ,
                                [UTD Test_Score] ,
                                [United Season Ticket Holder] ,
                                [United Seating Preference] ,
                                UnitedStayConnected ,
                                [Unsubscribe from CD] ,
                                cdi_facebook ,
                                cdi_linkedin ,
                                cdi_twitter ,
                                client_BWContactId ,
                                client_ambffsuppression ,
                                kore_BWBaseDate ,
                                kore_BWCompanyId ,
                                kore_BWContactId ,
                                kore_BWSequence ,
                                kore_CheckedOutById ,
                                kore_CheckedOutByIdName ,
                                kore_InvoiceBalance ,
                                kore_PrimaryAccountNumber ,
                                kore_SinceDate ,
                                kore_accountaliasidName ,
                                kore_address1milesfromfacility ,
                                new_AFYFNetwork ,
                                new_AMBFFNewsletter ,
                                new_AMBFFTrustees ,
                                new_Address1_MetroArea ,
                                new_AmericanExplorers ,
                                new_AtlantaFalconsNationalFootballLeague ,
                                new_AtlantaUnitedFCEventsFanPerksa ,
                                new_AtlantaUnitedFCMajorLeagueSoccer ,
                                new_BrokerFlag ,
                                new_ExcludeFromMBSEmails ,
                                new_FalconsNASSurveyLink ,
                                new_FanCouncilURL ,
                                new_FoundationSubscription ,
                                new_HasKidsunder18 ,
                                new_MLSFoundersSurveyLink ,
                                new_MLSLiveCode ,
                                new_MemoriesLastUpdated ,
                                new_MemoriesRedeemedCredits ,
                                new_MemoriesRegisteredMember ,
                                new_MemoriesRemainingCredits ,
                                new_MemoriesStartingCredits ,
                                new_NFLAccount ,
                                new_NFLAccountPassword ,
                                new_NFLMC1 ,
                                new_NFLMCCode1 ,
                                new_NFLMCCode2 ,
                                new_NFLMCCode3 ,
                                new_NFLMCCode4 ,
                                new_NFLMCURL2 ,
                                new_NSCheckedOutBy ,
                                new_NSCheckedOutByName ,
                                new_NSLicenseeName ,
                                new_RelocationDateTime ,
                                new_SponsorshipCheckedOutBy ,
                                new_SponsorshipCheckedOutByName ,
                                new_Subscription_EReport ,
                                new_Subscription_GearMail ,
                                new_Subscription_MLSSubscription ,
                                new_Subscription_Postgame_STH ,
                                new_Subscription_PreferredPartner ,
                                new_Subscription_Pregame_STH ,
                                new_Subscription_TicketSuiteSales ,
                                new_Subscription_Ticket_Offers ,
                                new_UnitedCheckedOutBy ,
                                new_UnitedCheckedOutByName ,
                                new_VirtualseatView ,
                                new_WNPFNetwork ,
                                new_new_subscription_MLSOfficialGearMail ,
                                new_subscriptionNewStadiumInformationOffers ,
                                [CRM Sync ID] ,
                                [CRM Enable Sync] ,
                                [CRM Contact Type] ,
                                [CRM Account ID] ,
                                [CRM Sync ID 2] ,
                                Duplicate ,
                                [MBS Concert Garth Brooks 20170619] ,
                                [MBS Events] ,
                                [MBS Events Stay Informed] ,
                                [MBS Tour Interest 20170628] ,
                                [Web Form First Name] ,
                                [Web Form Last Name] ,
                                [Web Form Telephone1] ,
                                [Web Form Zip Code],
								ISNULL(NULLIF(PSL_Owner_SSB,'NULL'),'') PSL_Owner_SSB,
								ISNULL(NULLIF([2017_United_STM_Paid],'NULL'),'') [2017_United_STM_Paid],
								ISNULL(NULLIF(United_MultiPack_SSB,'NULL'),'') United_MultiPack_SSB, 
								ISNULL(NULLIF(United_SingleGameBuyer_SSB,'NULL'),'') United_SingleGameBuyer_SSB,
								ISNULL(NULLIF([2017_Falcons_STM_Paid],'NULL'),'') [2017_Falcons_STM_Paid],
								ISNULL(NULLIF(Falcons_SingleGameBuyer_SSB,'NULL'),'') Falcons_SingleGameBuyer_SSB
                      FROM      apietl.silverpop_exportList_0
                    ) a
        ) AS SOURCE
    ON TARGET.RECIPIENT_ID = SOURCE.RECIPIENT_ID
        AND TARGET.Email = SOURCE.Email
    WHEN MATCHED THEN
        UPDATE SET
               TARGET.RECIPIENT_ID = SOURCE.RECIPIENT_ID ,
               TARGET.Email = SOURCE.Email ,
               TARGET.[Opt In Date] = SOURCE.[Opt In Date] ,
               TARGET.[Opted Out] = SOURCE.[Opted Out] ,
               TARGET.[Opt In Details] = SOURCE.[Opt In Details] ,
               TARGET.[Email Type] = SOURCE.[Email Type] ,
               TARGET.[Opted Out Date] = SOURCE.[Opted Out Date] ,
               TARGET.[Opt Out Details] = SOURCE.[Opt Out Details] ,
               TARGET.[CRM Sync ID] = SOURCE.[CRM Sync ID] ,
               TARGET.[CRM Enable Sync] = SOURCE.[CRM Enable Sync] ,
               TARGET.[CRM Contact Type] = SOURCE.[CRM Contact Type] ,
               TARGET.[CRM Account ID] = SOURCE.[CRM Account ID] ,
               TARGET.[2016 PSL Payment Paid] = SOURCE.[2016 PSL Payment Paid] ,
               TARGET.[2017 PSL Amount Due] = SOURCE.[2017 PSL Amount Due] ,
               TARGET.[2017 PSL Payment Paid] = SOURCE.[2017 PSL Payment Paid] ,
               TARGET.[21 or older] = SOURCE.[21 or older] ,
               TARGET.[AF Season Schedule] = SOURCE.[AF Season Schedule] ,
               TARGET.[AF Ticket Offers] = SOURCE.[AF Ticket Offers] ,
               TARGET.AUExclusiveContentNotifications = SOURCE.AUExclusiveContentNotifications ,
               TARGET.AUInTheStadiumNotifications = SOURCE.AUInTheStadiumNotifications ,
               TARGET.AUMatchStartNotifications = SOURCE.AUMatchStartNotifications ,
               TARGET.AUParkingAndTransitNotifications = SOURCE.AUParkingAndTransitNotifications ,
               TARGET.AUScoringNotifications = SOURCE.AUScoringNotifications ,
               TARGET.AUTeamNewsNotifications = SOURCE.AUTeamNewsNotifications ,
               TARGET.[Academy Team] = SOURCE.[Academy Team] ,
               TARGET.[Academy Tried Out] = SOURCE.[Academy Tried Out] ,
               TARGET.[Additional Comments] = SOURCE.[Additional Comments] ,
               TARGET.Address1_City = SOURCE.Address1_City ,
               TARGET.Address1_Country = SOURCE.Address1_Country ,
               TARGET.Address1_County = SOURCE.Address1_County ,
               TARGET.Address1_Line1 = SOURCE.Address1_Line1 ,
               TARGET.Address1_Line2 = SOURCE.Address1_Line2 ,
               TARGET.Address1_Line3 = SOURCE.Address1_Line3 ,
               TARGET.Address1_PostalCode = SOURCE.Address1_PostalCode ,
               TARGET.Address1_StateOrProvince = SOURCE.Address1_StateOrProvince ,
               TARGET.[Agree Official Rules] = SOURCE.[Agree Official Rules] ,
               TARGET.AllowSMS = SOURCE.AllowSMS ,
               TARGET.[Appointment Time] = SOURCE.[Appointment Time] ,
               TARGET.AssistantName = SOURCE.AssistantName ,
               TARGET.AssistantPhone = SOURCE.AssistantPhone ,
               TARGET.[Associated Archtics ID Suite Owner Admin] = SOURCE.[Associated Archtics ID Suite Owner Admin] ,
               TARGET.BirthDate = SOURCE.BirthDate ,
               TARGET.[CRM Sync ID 2] = SOURCE.[CRM Sync ID 2] ,
               TARGET.CRM_Contact_ID = SOURCE.CRM_Contact_ID ,
               TARGET.Company = SOURCE.Company ,
               TARGET.[Corporate Client or Employee Entertainment] = SOURCE.[Corporate Client or Employee Entertainment] ,
               TARGET.[Corporate Entertainment] = SOURCE.[Corporate Entertainment] ,
               TARGET.[Current Stadium Employee] = SOURCE.[Current Stadium Employee] ,
               TARGET.DoNotBulkEMail = SOURCE.DoNotBulkEMail ,
               TARGET.DoNotBulkPostalMail = SOURCE.DoNotBulkPostalMail ,
               TARGET.DoNotEMail = SOURCE.DoNotEMail ,
               TARGET.DoNotPostalMail = SOURCE.DoNotPostalMail ,
               TARGET.Duplicate = SOURCE.Duplicate ,
               TARGET.[Executive Member] = SOURCE.[Executive Member] ,
               TARGET.[Falcons Group] = SOURCE.[Falcons Group] ,
               TARGET.[Falcons Home Opponents] = SOURCE.[Falcons Home Opponents] ,
               TARGET.[Falcons Insider] = SOURCE.[Falcons Insider] ,
               TARGET.[Falcons SGB TE TF] = SOURCE.[Falcons SGB TE TF] ,
               TARGET.[Falcons Season Ticket Holder] = SOURCE.[Falcons Season Ticket Holder] ,
               TARGET.[Falcons Season Tix Due] = SOURCE.[Falcons Season Tix Due] ,
               TARGET.[Falcons Seating Preference] = SOURCE.[Falcons Seating Preference] ,
               TARGET.FirstName = SOURCE.FirstName ,
               TARGET.[Founding Members no seats] = SOURCE.[Founding Members no seats] ,
               TARGET.[Founding Members with seats] = SOURCE.[Founding Members with seats] ,
               TARGET.FullName = SOURCE.FullName ,
               TARGET.[GA Dome Premium Events] = SOURCE.[GA Dome Premium Events] ,
               TARGET.[GA Dome Seating Preferences] = SOURCE.[GA Dome Seating Preferences] ,
               TARGET.GenderCode = SOURCE.GenderCode ,
               TARGET.[Group Size] = SOURCE.[Group Size] ,
               TARGET.[Group Type] = SOURCE.[Group Type] ,
               TARGET.HasChildrenCode = SOURCE.HasChildrenCode ,
               TARGET.JobTitle = SOURCE.JobTitle ,
               TARGET.[KIA Account] = SOURCE.[KIA Account] ,
               TARGET.KORE_Type = SOURCE.KORE_Type ,
               TARGET.LastName = SOURCE.LastName ,
               TARGET.Last_Click = SOURCE.Last_Click ,
               TARGET.Last_Open = SOURCE.Last_Open ,
               TARGET.Last_Sent = SOURCE.Last_Sent ,
               TARGET.[MBS Concert Garth Brooks 20170619] = SOURCE.[MBS Concert Garth Brooks 20170619] ,
               TARGET.[MBS Events] = SOURCE.[MBS Events] ,
               TARGET.[MBS Events Stay Informed] = SOURCE.[MBS Events Stay Informed] ,
               TARGET.[MBS Hiring Emails] = SOURCE.[MBS Hiring Emails] ,
               TARGET.[MBS Seating Interest] = SOURCE.[MBS Seating Interest] ,
               TARGET.[MBS Tour Interest 20170628] = SOURCE.[MBS Tour Interest 20170628] ,
               TARGET.MiddleName = SOURCE.MiddleName ,
               TARGET.[Mobile User Id] = SOURCE.[Mobile User Id] ,
               TARGET.MobilePhone = SOURCE.MobilePhone ,
               TARGET.[My Finder] = SOURCE.[My Finder] ,
               TARGET.[Opt Out of Arthur M Blank Foundation Email Communication] = SOURCE.[Opt Out of Arthur M Blank Foundation Email Communication] ,
               TARGET.[Opt Out of Atlanta Falcons Email Communication] = SOURCE.[Opt Out of Atlanta Falcons Email Communication] ,
               TARGET.[Opt Out of Atlanta United Email Communication] = SOURCE.[Opt Out of Atlanta United Email Communication] ,
               TARGET.[PSL Owner] = SOURCE.[PSL Owner] ,
               TARGET.[Part Time Positions] = SOURCE.[Part Time Positions] ,
               TARGET.[Phone Call Opt In] = SOURCE.[Phone Call Opt In] ,
               TARGET.[Playoff Payment] = SOURCE.[Playoff Payment] ,
               TARGET.[Preferred Partner] = SOURCE.[Preferred Partner] ,
               TARGET.[Preferred Ticket Price] = SOURCE.[Preferred Ticket Price] ,
               TARGET.PreferredLanguage = SOURCE.PreferredLanguage ,
               TARGET.[Primary Rep] = SOURCE.[Primary Rep] ,
               TARGET.[Primary Rep Email] = SOURCE.[Primary Rep Email] ,
               TARGET.[Primary Rep Name] = SOURCE.[Primary Rep Name] ,
               TARGET.[Primary Rep Phone] = SOURCE.[Primary Rep Phone] ,
               TARGET.[Question or Comment] = SOURCE.[Question or Comment] ,
               TARGET.Salutation = SOURCE.Salutation ,
               TARGET.[Seating Level Preference] = SOURCE.[Seating Level Preference] ,
               TARGET.[Send Hour] = SOURCE.[Send Hour] ,
               TARGET.StateCode = SOURCE.StateCode ,
               TARGET.Suffix = SOURCE.Suffix ,
               TARGET.[Team Member Referral] = SOURCE.[Team Member Referral] ,
               TARGET.[Team Member Requirements] = SOURCE.[Team Member Requirements] ,
               TARGET.Telephone1 = SOURCE.Telephone1 ,
               TARGET.Telephone2 = SOURCE.Telephone2 ,
               TARGET.[UTD Acct Number] = SOURCE.[UTD Acct Number] ,
               TARGET.[UTD Event Sign Up] = SOURCE.[UTD Event Sign Up] ,
               TARGET.[UTD Group] = SOURCE.[UTD Group] ,
               --TARGET.[UTD Group Type] = SOURCE.[UTD Group Type] ,
               TARGET.[UTD Group Size] = SOURCE.[UTD Group Size] ,
               TARGET.[UTD Home Opponents] = SOURCE.[UTD Home Opponents] ,
               TARGET.[UTD Multi Game] = SOURCE.[UTD Multi Game] ,
               TARGET.[UTD SGB TE TF] = SOURCE.[UTD SGB TE TF] ,
               TARGET.[UTD Season Schedule] = SOURCE.[UTD Season Schedule] ,
               TARGET.[UTD Season Tix Due] = SOURCE.[UTD Season Tix Due] ,
               TARGET.[UTD Seating Preferences] = SOURCE.[UTD Seating Preferences] ,
               TARGET.[UTD Test_Behavior] = SOURCE.[UTD Test_Behavior] ,
               TARGET.[UTD Test_Rank] = SOURCE.[UTD Test_Rank] ,
               TARGET.[UTD Test_Score] = SOURCE.[UTD Test_Score] ,
               TARGET.[United Season Ticket Holder] = SOURCE.[United Season Ticket Holder] ,
               TARGET.[United Seating Preference] = SOURCE.[United Seating Preference] ,
               TARGET.UnitedStayConnected = SOURCE.UnitedStayConnected ,
               TARGET.[Unsubscribe from CD] = SOURCE.[Unsubscribe from CD] ,
               TARGET.[Web Form First Name] = SOURCE.[Web Form First Name] ,
               TARGET.[Web Form Last Name] = SOURCE.[Web Form Last Name] ,
               TARGET.[Web Form Telephone1] = SOURCE.[Web Form Telephone1] ,
               TARGET.[Web Form Zip Code] = SOURCE.[Web Form Zip Code] ,
               TARGET.cdi_facebook = SOURCE.cdi_facebook ,
               TARGET.cdi_linkedin = SOURCE.cdi_linkedin ,
               TARGET.cdi_twitter = SOURCE.cdi_twitter ,
               TARGET.client_BWContactId = SOURCE.client_BWContactId ,
               TARGET.client_ambffsuppression = SOURCE.client_ambffsuppression ,
               TARGET.kore_BWBaseDate = SOURCE.kore_BWBaseDate ,
               TARGET.kore_BWCompanyId = SOURCE.kore_BWCompanyId ,
               TARGET.kore_BWContactId = SOURCE.kore_BWContactId ,
               TARGET.kore_BWSequence = SOURCE.kore_BWSequence ,
               TARGET.kore_CheckedOutById = SOURCE.kore_CheckedOutById ,
               TARGET.kore_CheckedOutByIdName = SOURCE.kore_CheckedOutByIdName ,
               TARGET.kore_InvoiceBalance = SOURCE.kore_InvoiceBalance ,
               TARGET.kore_PrimaryAccountNumber = SOURCE.kore_PrimaryAccountNumber ,
               TARGET.kore_SinceDate = SOURCE.kore_SinceDate ,
               TARGET.kore_accountaliasidName = SOURCE.kore_accountaliasidName ,
               TARGET.kore_address1milesfromfacility = SOURCE.kore_address1milesfromfacility ,
               TARGET.new_AFYFNetwork = SOURCE.new_AFYFNetwork ,
               TARGET.new_AMBFFNewsletter = SOURCE.new_AMBFFNewsletter ,
               TARGET.new_AMBFFTrustees = SOURCE.new_AMBFFTrustees ,
               TARGET.new_Address1_MetroArea = SOURCE.new_Address1_MetroArea ,
               TARGET.new_AmericanExplorers = SOURCE.new_AmericanExplorers ,
               TARGET.new_AtlantaFalconsNationalFootballLeague = SOURCE.new_AtlantaFalconsNationalFootballLeague ,
               TARGET.new_AtlantaUnitedFCEventsFanPerksa = SOURCE.new_AtlantaUnitedFCEventsFanPerksa ,
               TARGET.new_AtlantaUnitedFCMajorLeagueSoccer = SOURCE.new_AtlantaUnitedFCMajorLeagueSoccer ,
               TARGET.new_BrokerFlag = SOURCE.new_BrokerFlag ,
               TARGET.new_ExcludeFromMBSEmails = SOURCE.new_ExcludeFromMBSEmails ,
               TARGET.new_FalconsNASSurveyLink = SOURCE.new_FalconsNASSurveyLink ,
               TARGET.new_FanCouncilURL = SOURCE.new_FanCouncilURL ,
               TARGET.new_FoundationSubscription = SOURCE.new_FoundationSubscription ,
               TARGET.new_HasKidsunder18 = SOURCE.new_HasKidsunder18 ,
               TARGET.new_MLSFoundersSurveyLink = SOURCE.new_MLSFoundersSurveyLink ,
               TARGET.new_MLSLiveCode = SOURCE.new_MLSLiveCode ,
               TARGET.new_MemoriesLastUpdated = SOURCE.new_MemoriesLastUpdated ,
               TARGET.new_MemoriesRedeemedCredits = SOURCE.new_MemoriesRedeemedCredits ,
               TARGET.new_MemoriesRegisteredMember = SOURCE.new_MemoriesRegisteredMember ,
               TARGET.new_MemoriesRemainingCredits = SOURCE.new_MemoriesRemainingCredits ,
               TARGET.new_MemoriesStartingCredits = SOURCE.new_MemoriesStartingCredits ,
               TARGET.new_NFLAccount = SOURCE.new_NFLAccount ,
               TARGET.new_NFLAccountPassword = SOURCE.new_NFLAccountPassword ,
               TARGET.new_NFLMC1 = SOURCE.new_NFLMC1 ,
               TARGET.new_NFLMCCode1 = SOURCE.new_NFLMCCode1 ,
               TARGET.new_NFLMCCode2 = SOURCE.new_NFLMCCode2 ,
               TARGET.new_NFLMCCode3 = SOURCE.new_NFLMCCode3 ,
               TARGET.new_NFLMCCode4 = SOURCE.new_NFLMCCode4 ,
               TARGET.new_NFLMCURL2 = SOURCE.new_NFLMCURL2 ,
               TARGET.new_NSCheckedOutBy = SOURCE.new_NSCheckedOutBy ,
               TARGET.new_NSCheckedOutByName = SOURCE.new_NSCheckedOutByName ,
               TARGET.new_NSLicenseeName = SOURCE.new_NSLicenseeName ,
               TARGET.new_RelocationDateTime = SOURCE.new_RelocationDateTime ,
               TARGET.new_SponsorshipCheckedOutBy = SOURCE.new_SponsorshipCheckedOutBy ,
               TARGET.new_SponsorshipCheckedOutByName = SOURCE.new_SponsorshipCheckedOutByName ,
               TARGET.new_Subscription_EReport = SOURCE.new_Subscription_EReport ,
               TARGET.new_Subscription_GearMail = SOURCE.new_Subscription_GearMail ,
               TARGET.new_Subscription_MLSSubscription = SOURCE.new_Subscription_MLSSubscription ,
               TARGET.new_Subscription_Postgame_STH = SOURCE.new_Subscription_Postgame_STH ,
               TARGET.new_Subscription_PreferredPartner = SOURCE.new_Subscription_PreferredPartner ,
               TARGET.new_Subscription_Pregame_STH = SOURCE.new_Subscription_Pregame_STH ,
               TARGET.new_Subscription_TicketSuiteSales = SOURCE.new_Subscription_TicketSuiteSales ,
               TARGET.new_Subscription_Ticket_Offers = SOURCE.new_Subscription_Ticket_Offers ,
               TARGET.new_UnitedCheckedOutBy = SOURCE.new_UnitedCheckedOutBy ,
               TARGET.new_UnitedCheckedOutByName = SOURCE.new_UnitedCheckedOutByName ,
               TARGET.new_VirtualseatView = SOURCE.new_VirtualseatView ,
               TARGET.new_WNPFNetwork = SOURCE.new_WNPFNetwork ,
               TARGET.new_new_subscription_MLSOfficialGearMail = SOURCE.new_new_subscription_MLSOfficialGearMail ,
               TARGET.new_subscriptionNewStadiumInformationOffers = SOURCE.new_subscriptionNewStadiumInformationOffers ,
			   TARGET.PSL_Owner_SSB=SOURCE.PSL_Owner_SSB ,
			   TARGET.[2017_United_STM_Paid]=SOURCE.[2017_United_STM_Paid] ,
			   TARGET.United_MultiPack_SSB=SOURCE.United_MultiPack_SSB , 
			   TARGET.United_SingleGameBuyer_SSB=SOURCE.United_SingleGameBuyer_SSB ,
			   TARGET.[2017_Falcons_STM_Paid]=SOURCE.[2017_Falcons_STM_Paid] ,
			   TARGET.Falcons_SingleGameBuyer_SSB=SOURCE.Falcons_SingleGameBuyer_SSB,
               TARGET.ETL__UpdatedDate = GETDATE()
    WHEN NOT MATCHED THEN
        INSERT ( RECIPIENT_ID ,
                 Email ,
                 [Opt In Date] ,
                 [Opted Out] ,
                 [Opt In Details] ,
                 [Email Type] ,
                 [Opted Out Date] ,
                 [Opt Out Details] ,
                -- [CRM Lead Source] ,
                 [CRM Sync ID] ,
                 [CRM Enable Sync] ,
                 [CRM Contact Type] ,
                 [CRM Account ID] ,
                 --[Last Modified Date] ,
                 [2016 PSL Payment Paid] ,
                 [2017 PSL Amount Due] ,
                 [2017 PSL Payment Paid] ,
                 [21 or older] ,
                 [AF Season Schedule] ,
                 [AF Ticket Offers] ,
                 AUExclusiveContentNotifications ,
                 AUInTheStadiumNotifications ,
                 AUMatchStartNotifications ,
                 AUParkingAndTransitNotifications ,
                 AUScoringNotifications ,
                 AUTeamNewsNotifications ,
                 [Academy Team] ,
                 [Academy Tried Out] ,
                 [Additional Comments] ,
                 Address1_City ,
                 Address1_Country ,
                 Address1_County ,
                 Address1_Line1 ,
                 Address1_Line2 ,
                 Address1_Line3 ,
                 Address1_PostalCode ,
                 Address1_StateOrProvince ,
                 [Agree Official Rules] ,
                 AllowSMS ,
                 [Appointment Time] ,
                 AssistantName ,
                 AssistantPhone ,
                 [Associated Archtics ID Suite Owner Admin] ,
                 BirthDate ,
                 [CRM Sync ID 2] ,
                 CRM_Contact_ID ,
                 Company ,
                 [Corporate Client or Employee Entertainment] ,
                 [Corporate Entertainment] ,
                 [Current Stadium Employee] ,
                 DoNotBulkEMail ,
                 DoNotBulkPostalMail ,
                 DoNotEMail ,
                 DoNotPostalMail ,
                 Duplicate ,
                 [Executive Member] ,
                 [Falcons Group] ,
                 [Falcons Home Opponents] ,
                 [Falcons Insider] ,
                 [Falcons SGB TE TF] ,
                 [Falcons Season Ticket Holder] ,
                 [Falcons Season Tix Due] ,
                 [Falcons Seating Preference] ,
                 FirstName ,
                 [Founding Members no seats] ,
                 [Founding Members with seats] ,
                 FullName ,
                 [GA Dome Premium Events] ,
                 [GA Dome Seating Preferences] ,
                 GenderCode ,
                 [Group Size] ,
                 [Group Type] ,
                 HasChildrenCode ,
                 JobTitle ,
                 [KIA Account] ,
                 KORE_Type ,
                 LastName ,
                 Last_Click ,
                 Last_Open ,
                 Last_Sent ,
                 [MBS Concert Garth Brooks 20170619] ,
                 [MBS Events] ,
                 [MBS Events Stay Informed] ,
                 [MBS Hiring Emails] ,
                 [MBS Seating Interest] ,
                 [MBS Tour Interest 20170628] ,
                 MiddleName ,
                 [Mobile User Id] ,
                 MobilePhone ,
                 [My Finder] ,
                 [Opt Out of Arthur M Blank Foundation Email Communication] ,
                 [Opt Out of Atlanta Falcons Email Communication] ,
                 [Opt Out of Atlanta United Email Communication] ,
                 [PSL Owner] ,
                 [Part Time Positions] ,
                 [Phone Call Opt In] ,
                 [Playoff Payment] ,
                 [Preferred Partner] ,
                 [Preferred Ticket Price] ,
                 PreferredLanguage ,
                 [Primary Rep] ,
                 [Primary Rep Email] ,
                 [Primary Rep Name] ,
                 [Primary Rep Phone] ,
                 [Question or Comment] ,
                 Salutation ,
                 [Seating Level Preference] ,
                 [Send Hour] ,
                 StateCode ,
                 Suffix ,
                 [Team Member Referral] ,
                 [Team Member Requirements] ,
                 Telephone1 ,
                 Telephone2 ,
                 [UTD Acct Number] ,
                 [UTD Event Sign Up] ,
                 [UTD Group] ,
                 --[UTD Group  Type] ,
                 [UTD Group Size] ,
                 [UTD Home Opponents] ,
                 [UTD Multi Game] ,
                 [UTD SGB TE TF] ,
                 [UTD Season Schedule] ,
                 [UTD Season Tix Due] ,
                 [UTD Seating Preferences] ,
                 [UTD Test_Behavior] ,
                 [UTD Test_Rank] ,
                 [UTD Test_Score] ,
                 [United Season Ticket Holder] ,
                 [United Seating Preference] ,
                 UnitedStayConnected ,
                 [Unsubscribe from CD] ,
                 [Web Form First Name] ,
                 [Web Form Last Name] ,
                 [Web Form Telephone1] ,
                 [Web Form Zip Code] ,
                 cdi_facebook ,
                 cdi_linkedin ,
                 cdi_twitter ,
                 client_BWContactId ,
                 client_ambffsuppression ,
                 kore_BWBaseDate ,
                 kore_BWCompanyId ,
                 kore_BWContactId ,
                 kore_BWSequence ,
                 kore_CheckedOutById ,
                 kore_CheckedOutByIdName ,
                 kore_InvoiceBalance ,
                 kore_PrimaryAccountNumber ,
                 kore_SinceDate ,
                 kore_accountaliasidName ,
                 kore_address1milesfromfacility ,
                 new_AFYFNetwork ,
                 new_AMBFFNewsletter ,
                 new_AMBFFTrustees ,
                 new_Address1_MetroArea ,
                 new_AmericanExplorers ,
                 new_AtlantaFalconsNationalFootballLeague ,
                 new_AtlantaUnitedFCEventsFanPerksa ,
                 new_AtlantaUnitedFCMajorLeagueSoccer ,
                 new_BrokerFlag ,
                 new_ExcludeFromMBSEmails ,
                 new_FalconsNASSurveyLink ,
                 new_FanCouncilURL ,
                 new_FoundationSubscription ,
                 new_HasKidsunder18 ,
                 new_MLSFoundersSurveyLink ,
                 new_MLSLiveCode ,
                 new_MemoriesLastUpdated ,
                 new_MemoriesRedeemedCredits ,
                 new_MemoriesRegisteredMember ,
                 new_MemoriesRemainingCredits ,
                 new_MemoriesStartingCredits ,
                 new_NFLAccount ,
                 new_NFLAccountPassword ,
                 new_NFLMC1 ,
                 new_NFLMCCode1 ,
                 new_NFLMCCode2 ,
                 new_NFLMCCode3 ,
                 new_NFLMCCode4 ,
                 new_NFLMCURL2 ,
                 new_NSCheckedOutBy ,
                 new_NSCheckedOutByName ,
                 new_NSLicenseeName ,
                 new_RelocationDateTime ,
                 new_SponsorshipCheckedOutBy ,
                 new_SponsorshipCheckedOutByName ,
                 new_Subscription_EReport ,
                 new_Subscription_GearMail ,
                 new_Subscription_MLSSubscription ,
                 new_Subscription_Postgame_STH ,
                 new_Subscription_PreferredPartner ,
                 new_Subscription_Pregame_STH ,
                 new_Subscription_TicketSuiteSales ,
                 new_Subscription_Ticket_Offers ,
                 new_UnitedCheckedOutBy ,
                 new_UnitedCheckedOutByName ,
                 new_VirtualseatView ,
                 new_WNPFNetwork ,
                 new_new_subscription_MLSOfficialGearMail ,
                 new_subscriptionNewStadiumInformationOffers ,
				 PSL_Owner_SSB ,
				 [2017_United_STM_Paid] ,
				 United_MultiPack_SSB , 
				 United_SingleGameBuyer_SSB ,
				 [2017_Falcons_STM_Paid] ,
				 Falcons_SingleGameBuyer_SSB,
                 ETL__CreatedDate ,
                 ETL__UpdatedDate 
               )
        VALUES ( SOURCE.RECIPIENT_ID ,
                 SOURCE.Email ,
                 SOURCE.[Opt In Date] ,
                 SOURCE.[Opted Out] ,
                 SOURCE.[Opt In Details] ,
                 SOURCE.[Email Type] ,
                 SOURCE.[Opted Out Date] ,
                 SOURCE.[Opt Out Details] ,
                 --SOURCE.[CRM Lead Source] ,
                 SOURCE.[CRM Sync ID] ,
                 SOURCE.[CRM Enable Sync] ,
                 SOURCE.[CRM Contact Type] ,
                 SOURCE.[CRM Account ID] ,
                 --SOURCE.[Last Modified Date] ,
                 SOURCE.[2016 PSL Payment Paid] ,
                 SOURCE.[2017 PSL Amount Due] ,
                 SOURCE.[2017 PSL Payment Paid] ,
                 SOURCE.[21 or older] ,
                 SOURCE.[AF Season Schedule] ,
                 SOURCE.[AF Ticket Offers] ,
                 SOURCE.AUExclusiveContentNotifications ,
                 SOURCE.AUInTheStadiumNotifications ,
                 SOURCE.AUMatchStartNotifications ,
                 SOURCE.AUParkingAndTransitNotifications ,
                 SOURCE.AUScoringNotifications ,
                 SOURCE.AUTeamNewsNotifications ,
                 SOURCE.[Academy Team] ,
                 SOURCE.[Academy Tried Out] ,
                 SOURCE.[Additional Comments] ,
                 SOURCE.Address1_City ,
                 SOURCE.Address1_Country ,
                 SOURCE.Address1_County ,
                 SOURCE.Address1_Line1 ,
                 SOURCE.Address1_Line2 ,
                 SOURCE.Address1_Line3 ,
                 SOURCE.Address1_PostalCode ,
                 SOURCE.Address1_StateOrProvince ,
                 SOURCE.[Agree Official Rules] ,
                 SOURCE.AllowSMS ,
                 SOURCE.[Appointment Time] ,
                 SOURCE.AssistantName ,
                 SOURCE.AssistantPhone ,
                 SOURCE.[Associated Archtics ID Suite Owner Admin] ,
                 SOURCE.BirthDate ,
                 SOURCE.[CRM Sync ID 2] ,
                 SOURCE.CRM_Contact_ID ,
                 SOURCE.Company ,
                 SOURCE.[Corporate Client or Employee Entertainment] ,
                 SOURCE.[Corporate Entertainment] ,
                 SOURCE.[Current Stadium Employee] ,
                 SOURCE.DoNotBulkEMail ,
                 SOURCE.DoNotBulkPostalMail ,
                 SOURCE.DoNotEMail ,
                 SOURCE.DoNotPostalMail ,
                 SOURCE.Duplicate ,
                 SOURCE.[Executive Member] ,
                 SOURCE.[Falcons Group] ,
                 SOURCE.[Falcons Home Opponents] ,
                 SOURCE.[Falcons Insider] ,
                 SOURCE.[Falcons SGB TE TF] ,
                 SOURCE.[Falcons Season Ticket Holder] ,
                 SOURCE.[Falcons Season Tix Due] ,
                 SOURCE.[Falcons Seating Preference] ,
                 SOURCE.FirstName ,
                 SOURCE.[Founding Members no seats] ,
                 SOURCE.[Founding Members with seats] ,
                 SOURCE.FullName ,
                 SOURCE.[GA Dome Premium Events] ,
                 SOURCE.[GA Dome Seating Preferences] ,
                 SOURCE.GenderCode ,
                 SOURCE.[Group Size] ,
                 SOURCE.[Group Type] ,
                 SOURCE.HasChildrenCode ,
                 SOURCE.JobTitle ,
                 SOURCE.[KIA Account] ,
                 SOURCE.KORE_Type ,
                 SOURCE.LastName ,
                 SOURCE.Last_Click ,
                 SOURCE.Last_Open ,
                 SOURCE.Last_Sent ,
                 SOURCE.[MBS Concert Garth Brooks 20170619] ,
                 SOURCE.[MBS Events] ,
                 SOURCE.[MBS Events Stay Informed] ,
                 SOURCE.[MBS Hiring Emails] ,
                 SOURCE.[MBS Seating Interest] ,
                 SOURCE.[MBS Tour Interest 20170628] ,
                 SOURCE.MiddleName ,
                 SOURCE.[Mobile User Id] ,
                 SOURCE.MobilePhone ,
                 SOURCE.[My Finder] ,
                 SOURCE.[Opt Out of Arthur M Blank Foundation Email Communication] ,
                 SOURCE.[Opt Out of Atlanta Falcons Email Communication] ,
                 SOURCE.[Opt Out of Atlanta United Email Communication] ,
                 SOURCE.[PSL Owner] ,
                 SOURCE.[Part Time Positions] ,
                 SOURCE.[Phone Call Opt In] ,
                 SOURCE.[Playoff Payment] ,
                 SOURCE.[Preferred Partner] ,
                 SOURCE.[Preferred Ticket Price] ,
                 SOURCE.PreferredLanguage ,
                 SOURCE.[Primary Rep] ,
                 SOURCE.[Primary Rep Email] ,
                 SOURCE.[Primary Rep Name] ,
                 SOURCE.[Primary Rep Phone] ,
                 SOURCE.[Question or Comment] ,
                 SOURCE.Salutation ,
                 SOURCE.[Seating Level Preference] ,
                 SOURCE.[Send Hour] ,
                 SOURCE.StateCode ,
                 SOURCE.Suffix ,
                 SOURCE.[Team Member Referral] ,
                 SOURCE.[Team Member Requirements] ,
                 SOURCE.Telephone1 ,
                 SOURCE.Telephone2 ,
                 SOURCE.[UTD Acct Number] ,
                 SOURCE.[UTD Event Sign Up] ,
                 SOURCE.[UTD Group] ,
                 --SOURCE.[UTD Group Type] ,
                 SOURCE.[UTD Group Size] ,
                 SOURCE.[UTD Home Opponents] ,
                 SOURCE.[UTD Multi Game] ,
                 SOURCE.[UTD SGB TE TF] ,
                 SOURCE.[UTD Season Schedule] ,
                 SOURCE.[UTD Season Tix Due] ,
                 SOURCE.[UTD Seating Preferences] ,
                 SOURCE.[UTD Test_Behavior] ,
                 SOURCE.[UTD Test_Rank] ,
                 SOURCE.[UTD Test_Score] ,
                 SOURCE.[United Season Ticket Holder] ,
                 SOURCE.[United Seating Preference] ,
                 SOURCE.UnitedStayConnected ,
                 SOURCE.[Unsubscribe from CD] ,
                 SOURCE.[Web Form First Name] ,
                 SOURCE.[Web Form Last Name] ,
                 SOURCE.[Web Form Telephone1] ,
                 SOURCE.[Web Form Zip Code] ,
                 SOURCE.cdi_facebook ,
                 SOURCE.cdi_linkedin ,
                 SOURCE.cdi_twitter ,
                 SOURCE.client_BWContactId ,
                 SOURCE.client_ambffsuppression ,
                 SOURCE.kore_BWBaseDate ,
                 SOURCE.kore_BWCompanyId ,
                 SOURCE.kore_BWContactId ,
                 SOURCE.kore_BWSequence ,
                 SOURCE.kore_CheckedOutById ,
                 SOURCE.kore_CheckedOutByIdName ,
                 SOURCE.kore_InvoiceBalance ,
                 SOURCE.kore_PrimaryAccountNumber ,
                 SOURCE.kore_SinceDate ,
                 SOURCE.kore_accountaliasidName ,
                 SOURCE.kore_address1milesfromfacility ,
                 SOURCE.new_AFYFNetwork ,
                 SOURCE.new_AMBFFNewsletter ,
                 SOURCE.new_AMBFFTrustees ,
                 SOURCE.new_Address1_MetroArea ,
                 SOURCE.new_AmericanExplorers ,
                 SOURCE.new_AtlantaFalconsNationalFootballLeague ,
                 SOURCE.new_AtlantaUnitedFCEventsFanPerksa ,
                 SOURCE.new_AtlantaUnitedFCMajorLeagueSoccer ,
                 SOURCE.new_BrokerFlag ,
                 SOURCE.new_ExcludeFromMBSEmails ,
                 SOURCE.new_FalconsNASSurveyLink ,
                 SOURCE.new_FanCouncilURL ,
                 SOURCE.new_FoundationSubscription ,
                 SOURCE.new_HasKidsunder18 ,
                 SOURCE.new_MLSFoundersSurveyLink ,
                 SOURCE.new_MLSLiveCode ,
                 SOURCE.new_MemoriesLastUpdated ,
                 SOURCE.new_MemoriesRedeemedCredits ,
                 SOURCE.new_MemoriesRegisteredMember ,
                 SOURCE.new_MemoriesRemainingCredits ,
                 SOURCE.new_MemoriesStartingCredits ,
                 SOURCE.new_NFLAccount ,
                 SOURCE.new_NFLAccountPassword ,
                 SOURCE.new_NFLMC1 ,
                 SOURCE.new_NFLMCCode1 ,
                 SOURCE.new_NFLMCCode2 ,
                 SOURCE.new_NFLMCCode3 ,
                 SOURCE.new_NFLMCCode4 ,
                 SOURCE.new_NFLMCURL2 ,
                 SOURCE.new_NSCheckedOutBy ,
                 SOURCE.new_NSCheckedOutByName ,
                 SOURCE.new_NSLicenseeName ,
                 SOURCE.new_RelocationDateTime ,
                 SOURCE.new_SponsorshipCheckedOutBy ,
                 SOURCE.new_SponsorshipCheckedOutByName ,
                 SOURCE.new_Subscription_EReport ,
                 SOURCE.new_Subscription_GearMail ,
                 SOURCE.new_Subscription_MLSSubscription ,
                 SOURCE.new_Subscription_Postgame_STH ,
                 SOURCE.new_Subscription_PreferredPartner ,
                 SOURCE.new_Subscription_Pregame_STH ,
                 SOURCE.new_Subscription_TicketSuiteSales ,
                 SOURCE.new_Subscription_Ticket_Offers ,
                 SOURCE.new_UnitedCheckedOutBy ,
                 SOURCE.new_UnitedCheckedOutByName ,
                 SOURCE.new_VirtualseatView ,
                 SOURCE.new_WNPFNetwork ,
                 SOURCE.new_new_subscription_MLSOfficialGearMail ,
                 SOURCE.new_subscriptionNewStadiumInformationOffers ,
				 SOURCE.PSL_Owner_SSB ,
				 SOURCE.[2017_United_STM_Paid] ,
				 SOURCE.United_MultiPack_SSB , 
				 SOURCE.United_SingleGameBuyer_SSB ,
				 SOURCE.[2017_Falcons_STM_Paid] ,
				 SOURCE.Falcons_SingleGameBuyer_SSB,
                 GETDATE() ,
                 GETDATE()
               );



GO
