SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROCEDURE [etl].[ProdCopy_ContactExtensionBase]
(
	@BatchId INT = 0,
	@Options NVARCHAR(MAX) = null
)
AS 

BEGIN
/**************************************Comments***************************************
**************************************************************************************
Mod #:  1
Name:     dbo
Date:     12/16/2015
Comments: Initial creation
*************************************************************************************/

DECLARE @RunTime DATETIME = GETDATE()

DECLARE @ExecutionId uniqueidentifier = newid();
DECLARE @ProcedureName NVARCHAR(255) = OBJECT_SCHEMA_NAME(@@PROCID) + '.' + OBJECT_NAME(@@PROCID);
DECLARE @SrcRowCount INT = ISNULL((SELECT CONVERT(VARCHAR, COUNT(*)) FROM ProdCopyStg.ContactExtensionBase),'0');	
DECLARE @SrcDataSize NVARCHAR(255) = '0'

BEGIN TRY 

PRINT 'Execution Id: ' + CONVERT(NVARCHAR(100),@ExecutionId)

SELECT CAST(NULL AS BINARY(32)) ETL_DeltaHashKey, ETL_UpdatedDate, ETL_IsDeleted, ETL_DeletedDate, ContactId, KORE_address1_telephone1dncstatus, KORE_address1_telephone2dncstatus, KORE_address1_telephone3dncstatus, kore_address1milesfromfacility, KORE_address2_telephone1dncstatus, KORE_address2_telephone2dncstatus, KORE_address2_telephone3dncstatus, KORE_assistantphonedncstatus, KORE_AttentionName, KORE_ImportID, KORE_LastContacted, KORE_LastSync, KORE_ListAttributeName, KORE_ListAttributeValue, KORE_managerphonedncstatus, KORE_mobilephonedncstatus, KORE_SeniorityDate, KORE_telephone1DNCStatus, KORE_telephone1dncstatustype, KORE_telephone2dncstatus, KORE_telephone2dncstatustype, KORE_telephone3dncstatus, KORE_telephone3dncstatustype, KORE_Type, kore_countryid, kore_stateorprovinceid, kore_sourcemarketinglistid, kore_lastcontactedbyid, kore_AccountNumbers, kore_CheckedOutUntil, kore_CompanyName, kore_OptOutOfDuplicateDetection, kore_ParentCustomerIdStrippedName, kore_PrimaryAccountNumber, kore_TicketingContactType, kore_accountaliasid, kore_CheckedOutById, client_BWContactId, kore_BWBaseDate, kore_BWCompanyId, kore_BWContactId, kore_BWSequence, cdi_age, cdi_allowtextmessages, cdi_facebook, cdi_gender, cdi_grade, cdi_identifiedon, cdi_image, cdi_ip, cdi_latitude, cdi_linkedin, cdi_Longitude, cdi_partitionkey, cdi_rowkey, cdi_score, cdi_social, cdi_totalscore, cdi_twitter, cdi_visitorkey, new_DomeAccountNumber, new_DomeContractStart, new_DomeContractEnd, new_DomeContractExt, new_DomeContractEscalator, new_DomeSeats, new_somethingelse, new_ImportSource, new_MyFinder, new_GeorgiaDomeSeats, new_Source, new_Subscription_EReport, new_Subscription_Postgame_STH, new_Subscription_Pregame_STH, new_Subscription_GearMail, new_Subscription_TicketSuiteSales, new_Subscription_PreferredPartner, new_Subscription_Ticket_Offers, kore_InvoiceBalance, kore_invoicebalance_Base, kore_SinceDate, new_PIF_Amount, new_pif_amount_Base, new_5MonthlyPaymentAmt, new_5monthlypaymentamt_Base, new_40_60PaymentAmt, new_40_60paymentamt_Base, new_PersonalURL, new_FavoritePlayer, new_RelocationDateTime, new_NFLAccount, new_NFLAccountPassword, new_CurrentSeasonAccountHolder, new_Subscription_MLSSubscription, new_new_subscription_MLSOfficialGearMail, new_Address1_MetroArea, new_NFLMC1, new_NFLMCCode1, new_NFLMCURL2, new_NFLMCCode2, new_NFLMCCode3, new_NFLMCCode4, new_CurrentSpend, new_NSWaitlistConfirmed, kore_archticsids, kore_ExternalContactId, kore_GroupBuyer, kore_GroupCategory, kore_HeritageNationality, kore_MilesFromFacility, kore_MiniPlanHolder, kore_OverrideCheckoutExpiration, kore_PrimaryArchticsId, kore_SeasonTicketHolder, kore_SecondaryArchticsName, kore_SecondaryEmail, kore_SuiteBuyer, kore_GroupSalesRep, kore_SuiteSalesRep, kore_TicketingSalesRep, kore_TicketingServiceRep, li_CompanyId, li_MemberToken, new_SponsorshipCheckedOutBy, new_SponsorshipCheckedOutUntil, new_NSCheckedOutBy, new_NSCheckedOutUntil, new_AMBFFNewsletter, new_AFYFNetwork, new_WNPFNetwork, new_AmericanExplorers, new_AMBFFTrustees, KORE_IsBillingContact, KORE_IsPrimaryContact, KORE_sponsoraccountnumber, new_NSReservationDate, client_gpaccountnumber, client_GPCustomerClass, client_triggergp, new_NSAppointmentIdentifier, new_NSPURL, new_NSPasscode, new_NSRepEmail, new_NSRepPhone, new_MLSFoundersSurveyLink, new_NSLicenseeName, new_FoundationSubscription, new_FuturePhaseRep, new_FuturePhaseNotes, new_subscriptionNewStadiumInformationOffers, new_AllocatedSeatLocation, new_VirtualseatView, new_MLSLiveCode, new_NSReserveSeatInterest, new_NSClubSeatInterest, new_NSReserveInterest, new_NSClubInterest, new_NSSuiteInterest, new_BrokerFlag, new_FalconsNASSurveyLink, new_TypeOfGroup, new_MiscField, new_InterestType, new_NumberofSeats, new_InterestLevel, new_SeatingPreference, new_NumberofTickets, new_AtlantaUnitedFCMajorLeagueSoccer, new_AtlantaUnitedFCEventsFanPerksa, new_AtlantaFalconsNationalFootballLeague, new_FanCouncilURL, new_MemoriesStartingCredits, new_MemoriesRedeemedCredits, new_MemoriesRemainingCredits, new_MemoriesLastUpdated, new_MemoriesRegisteredMember, new_PSLAcctMgrPIN, new_TETicketsPurchased, new_TEGamesPurchased, new_TEMoneySpent, new_temoneyspent_Base, new_ExcludeFromMBSEmails, new_SGBGamesPurchased, new_SGBTicketsPurchased, new_SGBMoneySpent, new_sgbmoneyspent_Base, new_ATLUTDSeasonTickets, new_ATLUTDGroupTickets, new_ATLUTDSingleGameTickets, new_TopContact
INTO #SrcData
FROM ProdCopyStg.ContactExtensionBase

UPDATE #SrcData
SET ETL_DeltaHashKey = HASHBYTES('sha2_256', ISNULL(RTRIM(CONVERT(varchar(10),cdi_age)),'DBNULL_INT') + ISNULL(RTRIM(CONVERT(varchar(10),cdi_allowtextmessages)),'DBNULL_BIT') + ISNULL(RTRIM(cdi_facebook),'DBNULL_TEXT') + ISNULL(RTRIM(CONVERT(varchar(10),cdi_gender)),'DBNULL_BIT') + ISNULL(RTRIM(cdi_grade),'DBNULL_TEXT') + ISNULL(RTRIM(CONVERT(varchar(25),cdi_identifiedon)),'DBNULL_DATETIME') + ISNULL(RTRIM(cdi_image),'DBNULL_TEXT') + ISNULL(RTRIM(cdi_ip),'DBNULL_TEXT') + ISNULL(RTRIM(cdi_latitude),'DBNULL_TEXT') + ISNULL(RTRIM(cdi_linkedin),'DBNULL_TEXT') + ISNULL(RTRIM(cdi_Longitude),'DBNULL_TEXT') + ISNULL(RTRIM(cdi_partitionkey),'DBNULL_TEXT') + ISNULL(RTRIM(cdi_rowkey),'DBNULL_TEXT') + ISNULL(RTRIM(CONVERT(varchar(10),cdi_score)),'DBNULL_INT') + ISNULL(RTRIM(CONVERT(varchar(10),cdi_totalscore)),'DBNULL_INT') + ISNULL(RTRIM(cdi_twitter),'DBNULL_TEXT') + ISNULL(RTRIM(cdi_visitorkey),'DBNULL_TEXT') + ISNULL(RTRIM(client_BWContactId),'DBNULL_TEXT') + ISNULL(RTRIM(client_gpaccountnumber),'DBNULL_TEXT') + ISNULL(RTRIM(CONVERT(varchar(10),client_GPCustomerClass)),'DBNULL_INT') + ISNULL(RTRIM(CONVERT(varchar(10),client_triggergp)),'DBNULL_BIT') + ISNULL(RTRIM(ContactId),'DBNULL_TEXT') + ISNULL(RTRIM(CONVERT(varchar(25),ETL_DeletedDate)),'DBNULL_DATETIME') + ISNULL(RTRIM(ETL_DeltaHashKey),'DBNULL_TEXT') + ISNULL(RTRIM(CONVERT(varchar(10),ETL_IsDeleted)),'DBNULL_BIT') + ISNULL(RTRIM(CONVERT(varchar(25),ETL_UpdatedDate)),'DBNULL_DATETIME') + ISNULL(RTRIM(kore_accountaliasid),'DBNULL_TEXT') + ISNULL(RTRIM(kore_AccountNumbers),'DBNULL_TEXT') + ISNULL(RTRIM(CONVERT(varchar(10),KORE_address1_telephone1dncstatus)),'DBNULL_BIT') + ISNULL(RTRIM(CONVERT(varchar(10),KORE_address1_telephone2dncstatus)),'DBNULL_BIT') + ISNULL(RTRIM(CONVERT(varchar(10),KORE_address1_telephone3dncstatus)),'DBNULL_BIT') + ISNULL(RTRIM(CONVERT(varchar(25),kore_address1milesfromfacility)),'DBNULL_NUMBER') + ISNULL(RTRIM(CONVERT(varchar(10),KORE_address2_telephone1dncstatus)),'DBNULL_BIT') + ISNULL(RTRIM(CONVERT(varchar(10),KORE_address2_telephone2dncstatus)),'DBNULL_BIT') + ISNULL(RTRIM(CONVERT(varchar(10),KORE_address2_telephone3dncstatus)),'DBNULL_BIT') + ISNULL(RTRIM(kore_archticsids),'DBNULL_TEXT') + ISNULL(RTRIM(CONVERT(varchar(10),KORE_assistantphonedncstatus)),'DBNULL_BIT') + ISNULL(RTRIM(KORE_AttentionName),'DBNULL_TEXT') + ISNULL(RTRIM(kore_BWBaseDate),'DBNULL_TEXT') + ISNULL(RTRIM(kore_BWCompanyId),'DBNULL_TEXT') + ISNULL(RTRIM(kore_BWContactId),'DBNULL_TEXT') + ISNULL(RTRIM(CONVERT(varchar(10),kore_BWSequence)),'DBNULL_INT') + ISNULL(RTRIM(kore_CheckedOutById),'DBNULL_TEXT') + ISNULL(RTRIM(CONVERT(varchar(25),kore_CheckedOutUntil)),'DBNULL_DATETIME') + ISNULL(RTRIM(kore_CompanyName),'DBNULL_TEXT') + ISNULL(RTRIM(kore_countryid),'DBNULL_TEXT') + ISNULL(RTRIM(kore_ExternalContactId),'DBNULL_TEXT') + ISNULL(RTRIM(CONVERT(varchar(10),kore_GroupBuyer)),'DBNULL_BIT') + ISNULL(RTRIM(CONVERT(varchar(10),kore_GroupCategory)),'DBNULL_INT') + ISNULL(RTRIM(kore_GroupSalesRep),'DBNULL_TEXT') + ISNULL(RTRIM(kore_HeritageNationality),'DBNULL_TEXT') + ISNULL(RTRIM(KORE_ImportID),'DBNULL_TEXT') + ISNULL(RTRIM(kore_InvoiceBalance),'DBNULL_TEXT') + ISNULL(RTRIM(kore_invoicebalance_Base),'DBNULL_TEXT') + ISNULL(RTRIM(CONVERT(varchar(10),KORE_IsBillingContact)),'DBNULL_BIT') + ISNULL(RTRIM(CONVERT(varchar(10),KORE_IsPrimaryContact)),'DBNULL_BIT') + ISNULL(RTRIM(CONVERT(varchar(25),KORE_LastContacted)),'DBNULL_DATETIME') + ISNULL(RTRIM(kore_lastcontactedbyid),'DBNULL_TEXT') + ISNULL(RTRIM(CONVERT(varchar(25),KORE_LastSync)),'DBNULL_DATETIME') + ISNULL(RTRIM(KORE_ListAttributeName),'DBNULL_TEXT') + ISNULL(RTRIM(KORE_ListAttributeValue),'DBNULL_TEXT') + ISNULL(RTRIM(CONVERT(varchar(10),KORE_managerphonedncstatus)),'DBNULL_BIT') + ISNULL(RTRIM(CONVERT(varchar(25),kore_MilesFromFacility)),'DBNULL_NUMBER') + ISNULL(RTRIM(CONVERT(varchar(10),kore_MiniPlanHolder)),'DBNULL_BIT') + ISNULL(RTRIM(CONVERT(varchar(10),KORE_mobilephonedncstatus)),'DBNULL_BIT') + ISNULL(RTRIM(CONVERT(varchar(10),kore_OptOutOfDuplicateDetection)),'DBNULL_BIT') + ISNULL(RTRIM(CONVERT(varchar(10),kore_OverrideCheckoutExpiration)),'DBNULL_BIT') + ISNULL(RTRIM(kore_ParentCustomerIdStrippedName),'DBNULL_TEXT') + ISNULL(RTRIM(kore_PrimaryAccountNumber),'DBNULL_TEXT') + ISNULL(RTRIM(kore_PrimaryArchticsId),'DBNULL_TEXT') + ISNULL(RTRIM(CONVERT(varchar(10),kore_SeasonTicketHolder)),'DBNULL_BIT') + ISNULL(RTRIM(kore_SecondaryArchticsName),'DBNULL_TEXT') + ISNULL(RTRIM(kore_SecondaryEmail),'DBNULL_TEXT') + ISNULL(RTRIM(CONVERT(varchar(25),KORE_SeniorityDate)),'DBNULL_DATETIME') + ISNULL(RTRIM(CONVERT(varchar(25),kore_SinceDate)),'DBNULL_DATETIME') + ISNULL(RTRIM(kore_sourcemarketinglistid),'DBNULL_TEXT') + ISNULL(RTRIM(KORE_sponsoraccountnumber),'DBNULL_TEXT') + ISNULL(RTRIM(kore_stateorprovinceid),'DBNULL_TEXT') + ISNULL(RTRIM(CONVERT(varchar(10),kore_SuiteBuyer)),'DBNULL_BIT') + ISNULL(RTRIM(kore_SuiteSalesRep),'DBNULL_TEXT') + ISNULL(RTRIM(CONVERT(varchar(10),KORE_telephone1DNCStatus)),'DBNULL_BIT') + ISNULL(RTRIM(CONVERT(varchar(10),KORE_telephone1dncstatustype)),'DBNULL_INT') + ISNULL(RTRIM(CONVERT(varchar(10),KORE_telephone2dncstatus)),'DBNULL_BIT') + ISNULL(RTRIM(CONVERT(varchar(10),KORE_telephone2dncstatustype)),'DBNULL_INT') + ISNULL(RTRIM(CONVERT(varchar(10),KORE_telephone3dncstatus)),'DBNULL_BIT') + ISNULL(RTRIM(CONVERT(varchar(10),KORE_telephone3dncstatustype)),'DBNULL_INT') + ISNULL(RTRIM(CONVERT(varchar(10),kore_TicketingContactType)),'DBNULL_INT') + ISNULL(RTRIM(kore_TicketingSalesRep),'DBNULL_TEXT') + ISNULL(RTRIM(kore_TicketingServiceRep),'DBNULL_TEXT') + ISNULL(RTRIM(CONVERT(varchar(10),KORE_Type)),'DBNULL_INT') + ISNULL(RTRIM(CONVERT(varchar(10),li_CompanyId)),'DBNULL_INT') + ISNULL(RTRIM(li_MemberToken),'DBNULL_TEXT') + ISNULL(RTRIM(new_40_60PaymentAmt),'DBNULL_TEXT') + ISNULL(RTRIM(new_40_60paymentamt_Base),'DBNULL_TEXT') + ISNULL(RTRIM(new_5MonthlyPaymentAmt),'DBNULL_TEXT') + ISNULL(RTRIM(new_5monthlypaymentamt_Base),'DBNULL_TEXT') + ISNULL(RTRIM(new_Address1_MetroArea),'DBNULL_TEXT') + ISNULL(RTRIM(CONVERT(varchar(10),new_AFYFNetwork)),'DBNULL_BIT') + ISNULL(RTRIM(new_AllocatedSeatLocation),'DBNULL_TEXT') + ISNULL(RTRIM(CONVERT(varchar(10),new_AMBFFNewsletter)),'DBNULL_BIT') + ISNULL(RTRIM(CONVERT(varchar(10),new_AMBFFTrustees)),'DBNULL_BIT') + ISNULL(RTRIM(CONVERT(varchar(10),new_AmericanExplorers)),'DBNULL_BIT') + ISNULL(RTRIM(CONVERT(varchar(10),new_AtlantaFalconsNationalFootballLeague)),'DBNULL_BIT') + ISNULL(RTRIM(CONVERT(varchar(10),new_AtlantaUnitedFCEventsFanPerksa)),'DBNULL_BIT') + ISNULL(RTRIM(CONVERT(varchar(10),new_AtlantaUnitedFCMajorLeagueSoccer)),'DBNULL_BIT') + ISNULL(RTRIM(CONVERT(varchar(10),new_ATLUTDGroupTickets)),'DBNULL_BIT') + ISNULL(RTRIM(CONVERT(varchar(10),new_ATLUTDSeasonTickets)),'DBNULL_BIT') + ISNULL(RTRIM(CONVERT(varchar(10),new_ATLUTDSingleGameTickets)),'DBNULL_BIT') + ISNULL(RTRIM(CONVERT(varchar(10),new_BrokerFlag)),'DBNULL_BIT') + ISNULL(RTRIM(CONVERT(varchar(10),new_CurrentSeasonAccountHolder)),'DBNULL_BIT') + ISNULL(RTRIM(new_CurrentSpend),'DBNULL_TEXT') + ISNULL(RTRIM(new_DomeAccountNumber),'DBNULL_TEXT') + ISNULL(RTRIM(new_DomeContractEnd),'DBNULL_TEXT') + ISNULL(RTRIM(new_DomeContractEscalator),'DBNULL_TEXT') + ISNULL(RTRIM(new_DomeContractExt),'DBNULL_TEXT') + ISNULL(RTRIM(new_DomeContractStart),'DBNULL_TEXT') + ISNULL(RTRIM(CONVERT(varchar(10),new_ExcludeFromMBSEmails)),'DBNULL_INT') + ISNULL(RTRIM(new_FalconsNASSurveyLink),'DBNULL_TEXT') + ISNULL(RTRIM(new_FanCouncilURL),'DBNULL_TEXT') + ISNULL(RTRIM(CONVERT(varchar(10),new_FavoritePlayer)),'DBNULL_INT') + ISNULL(RTRIM(new_FoundationSubscription),'DBNULL_TEXT') + ISNULL(RTRIM(new_FuturePhaseNotes),'DBNULL_TEXT') + ISNULL(RTRIM(new_FuturePhaseRep),'DBNULL_TEXT') + ISNULL(RTRIM(new_GeorgiaDomeSeats),'DBNULL_TEXT') + ISNULL(RTRIM(new_ImportSource),'DBNULL_TEXT') + ISNULL(RTRIM(CONVERT(varchar(10),new_InterestLevel)),'DBNULL_INT') + ISNULL(RTRIM(CONVERT(varchar(10),new_InterestType)),'DBNULL_INT') + ISNULL(RTRIM(CONVERT(varchar(25),new_MemoriesLastUpdated)),'DBNULL_DATETIME') + ISNULL(RTRIM(CONVERT(varchar(10),new_MemoriesRedeemedCredits)),'DBNULL_INT') + ISNULL(RTRIM(CONVERT(varchar(10),new_MemoriesRegisteredMember)),'DBNULL_BIT') + ISNULL(RTRIM(CONVERT(varchar(10),new_MemoriesRemainingCredits)),'DBNULL_INT') + ISNULL(RTRIM(CONVERT(varchar(10),new_MemoriesStartingCredits)),'DBNULL_INT') + ISNULL(RTRIM(new_MiscField),'DBNULL_TEXT') + ISNULL(RTRIM(new_MLSFoundersSurveyLink),'DBNULL_TEXT') + ISNULL(RTRIM(new_MLSLiveCode),'DBNULL_TEXT') + ISNULL(RTRIM(new_MyFinder),'DBNULL_TEXT') + ISNULL(RTRIM(CONVERT(varchar(10),new_new_subscription_MLSOfficialGearMail)),'DBNULL_BIT') + ISNULL(RTRIM(new_NFLAccount),'DBNULL_TEXT') + ISNULL(RTRIM(new_NFLAccountPassword),'DBNULL_TEXT') + ISNULL(RTRIM(new_NFLMC1),'DBNULL_TEXT') + ISNULL(RTRIM(new_NFLMCCode1),'DBNULL_TEXT') + ISNULL(RTRIM(new_NFLMCCode2),'DBNULL_TEXT') + ISNULL(RTRIM(new_NFLMCCode3),'DBNULL_TEXT') + ISNULL(RTRIM(new_NFLMCCode4),'DBNULL_TEXT') + ISNULL(RTRIM(new_NFLMCURL2),'DBNULL_TEXT') + ISNULL(RTRIM(new_NSAppointmentIdentifier),'DBNULL_TEXT') + ISNULL(RTRIM(new_NSCheckedOutBy),'DBNULL_TEXT') + ISNULL(RTRIM(CONVERT(varchar(25),new_NSCheckedOutUntil)),'DBNULL_DATETIME') + ISNULL(RTRIM(CONVERT(varchar(10),new_NSClubInterest)),'DBNULL_BIT') + ISNULL(RTRIM(CONVERT(varchar(10),new_NSClubSeatInterest)),'DBNULL_INT') + ISNULL(RTRIM(new_NSLicenseeName),'DBNULL_TEXT') + ISNULL(RTRIM(new_NSPasscode),'DBNULL_TEXT') + ISNULL(RTRIM(new_NSPURL),'DBNULL_TEXT') + ISNULL(RTRIM(new_NSRepEmail),'DBNULL_TEXT') + ISNULL(RTRIM(new_NSRepPhone),'DBNULL_TEXT') + ISNULL(RTRIM(CONVERT(varchar(25),new_NSReservationDate)),'DBNULL_DATETIME') + ISNULL(RTRIM(CONVERT(varchar(10),new_NSReserveInterest)),'DBNULL_BIT') + ISNULL(RTRIM(CONVERT(varchar(10),new_NSReserveSeatInterest)),'DBNULL_INT') + ISNULL(RTRIM(CONVERT(varchar(10),new_NSSuiteInterest)),'DBNULL_BIT') + ISNULL(RTRIM(CONVERT(varchar(10),new_NSWaitlistConfirmed)),'DBNULL_BIT') + ISNULL(RTRIM(CONVERT(varchar(10),new_NumberofSeats)),'DBNULL_INT') + ISNULL(RTRIM(CONVERT(varchar(10),new_NumberofTickets)),'DBNULL_INT') + ISNULL(RTRIM(new_PersonalURL),'DBNULL_TEXT') + ISNULL(RTRIM(new_PIF_Amount),'DBNULL_TEXT') + ISNULL(RTRIM(new_pif_amount_Base),'DBNULL_TEXT') + ISNULL(RTRIM(new_PSLAcctMgrPIN),'DBNULL_TEXT') + ISNULL(RTRIM(new_RelocationDateTime),'DBNULL_TEXT') + ISNULL(RTRIM(CONVERT(varchar(10),new_SeatingPreference)),'DBNULL_INT') + ISNULL(RTRIM(CONVERT(varchar(10),new_SGBGamesPurchased)),'DBNULL_INT') + ISNULL(RTRIM(new_SGBMoneySpent),'DBNULL_TEXT') + ISNULL(RTRIM(new_sgbmoneyspent_Base),'DBNULL_TEXT') + ISNULL(RTRIM(CONVERT(varchar(10),new_SGBTicketsPurchased)),'DBNULL_INT') + ISNULL(RTRIM(new_somethingelse),'DBNULL_TEXT') + ISNULL(RTRIM(new_Source),'DBNULL_TEXT') + ISNULL(RTRIM(new_SponsorshipCheckedOutBy),'DBNULL_TEXT') + ISNULL(RTRIM(CONVERT(varchar(25),new_SponsorshipCheckedOutUntil)),'DBNULL_DATETIME') + ISNULL(RTRIM(CONVERT(varchar(10),new_Subscription_EReport)),'DBNULL_BIT') + ISNULL(RTRIM(CONVERT(varchar(10),new_Subscription_GearMail)),'DBNULL_BIT') + ISNULL(RTRIM(CONVERT(varchar(10),new_Subscription_MLSSubscription)),'DBNULL_BIT') + ISNULL(RTRIM(CONVERT(varchar(10),new_Subscription_Postgame_STH)),'DBNULL_BIT') + ISNULL(RTRIM(CONVERT(varchar(10),new_Subscription_PreferredPartner)),'DBNULL_BIT') + ISNULL(RTRIM(CONVERT(varchar(10),new_Subscription_Pregame_STH)),'DBNULL_BIT') + ISNULL(RTRIM(CONVERT(varchar(10),new_Subscription_Ticket_Offers)),'DBNULL_BIT') + ISNULL(RTRIM(CONVERT(varchar(10),new_Subscription_TicketSuiteSales)),'DBNULL_BIT') + ISNULL(RTRIM(CONVERT(varchar(10),new_subscriptionNewStadiumInformationOffers)),'DBNULL_BIT') + ISNULL(RTRIM(CONVERT(varchar(10),new_TEGamesPurchased)),'DBNULL_INT') + ISNULL(RTRIM(new_TEMoneySpent),'DBNULL_TEXT') + ISNULL(RTRIM(new_temoneyspent_Base),'DBNULL_TEXT') + ISNULL(RTRIM(CONVERT(varchar(10),new_TETicketsPurchased)),'DBNULL_INT') + ISNULL(RTRIM(CONVERT(varchar(10),new_TopContact)),'DBNULL_INT') + ISNULL(RTRIM(CONVERT(varchar(10),new_TypeOfGroup)),'DBNULL_INT') + ISNULL(RTRIM(new_VirtualseatView),'DBNULL_TEXT') + ISNULL(RTRIM(CONVERT(varchar(10),new_WNPFNetwork)),'DBNULL_BIT'))


CREATE NONCLUSTERED INDEX IDX_Load_Key ON #SrcData (ContactId)
CREATE NONCLUSTERED INDEX IDX_ETL_DeltaHashKey ON #SrcData (ETL_DeltaHashKey)



MERGE ProdCopy.ContactExtensionBase AS myTarget

USING (
	SELECT * FROM #SrcData
) AS mySource
    
	ON myTarget.ContactId = mySource.ContactId

WHEN MATCHED AND (
     ISNULL(mySource.ETL_DeltaHashKey,-1) <> ISNULL(myTarget.ETL_DeltaHashKey, -1)
	 )
THEN UPDATE SET
      myTarget.[ETL_UpdatedDate] = @RunTime
     ,myTarget.[ETL_DeltaHashKey] = mySource.[ETL_DeltaHashKey]
     ,myTarget.[ContactId] = mySource.[ContactId]
     ,myTarget.[KORE_address1_telephone1dncstatus] = mySource.[KORE_address1_telephone1dncstatus]
     ,myTarget.[KORE_address1_telephone2dncstatus] = mySource.[KORE_address1_telephone2dncstatus]
     ,myTarget.[KORE_address1_telephone3dncstatus] = mySource.[KORE_address1_telephone3dncstatus]
     ,myTarget.[kore_address1milesfromfacility] = mySource.[kore_address1milesfromfacility]
     ,myTarget.[KORE_address2_telephone1dncstatus] = mySource.[KORE_address2_telephone1dncstatus]
     ,myTarget.[KORE_address2_telephone2dncstatus] = mySource.[KORE_address2_telephone2dncstatus]
     ,myTarget.[KORE_address2_telephone3dncstatus] = mySource.[KORE_address2_telephone3dncstatus]
     ,myTarget.[KORE_assistantphonedncstatus] = mySource.[KORE_assistantphonedncstatus]
     ,myTarget.[KORE_AttentionName] = mySource.[KORE_AttentionName]
     ,myTarget.[KORE_ImportID] = mySource.[KORE_ImportID]
     ,myTarget.[KORE_LastContacted] = mySource.[KORE_LastContacted]
     ,myTarget.[KORE_LastSync] = mySource.[KORE_LastSync]
     ,myTarget.[KORE_ListAttributeName] = mySource.[KORE_ListAttributeName]
     ,myTarget.[KORE_ListAttributeValue] = mySource.[KORE_ListAttributeValue]
     ,myTarget.[KORE_managerphonedncstatus] = mySource.[KORE_managerphonedncstatus]
     ,myTarget.[KORE_mobilephonedncstatus] = mySource.[KORE_mobilephonedncstatus]
     ,myTarget.[KORE_SeniorityDate] = mySource.[KORE_SeniorityDate]
     ,myTarget.[KORE_telephone1DNCStatus] = mySource.[KORE_telephone1DNCStatus]
     ,myTarget.[KORE_telephone1dncstatustype] = mySource.[KORE_telephone1dncstatustype]
     ,myTarget.[KORE_telephone2dncstatus] = mySource.[KORE_telephone2dncstatus]
     ,myTarget.[KORE_telephone2dncstatustype] = mySource.[KORE_telephone2dncstatustype]
     ,myTarget.[KORE_telephone3dncstatus] = mySource.[KORE_telephone3dncstatus]
     ,myTarget.[KORE_telephone3dncstatustype] = mySource.[KORE_telephone3dncstatustype]
     ,myTarget.[KORE_Type] = mySource.[KORE_Type]
     ,myTarget.[kore_countryid] = mySource.[kore_countryid]
     ,myTarget.[kore_stateorprovinceid] = mySource.[kore_stateorprovinceid]
     ,myTarget.[kore_sourcemarketinglistid] = mySource.[kore_sourcemarketinglistid]
     ,myTarget.[kore_lastcontactedbyid] = mySource.[kore_lastcontactedbyid]
     ,myTarget.[kore_AccountNumbers] = mySource.[kore_AccountNumbers]
     ,myTarget.[kore_CheckedOutUntil] = mySource.[kore_CheckedOutUntil]
     ,myTarget.[kore_CompanyName] = mySource.[kore_CompanyName]
     ,myTarget.[kore_OptOutOfDuplicateDetection] = mySource.[kore_OptOutOfDuplicateDetection]
     ,myTarget.[kore_ParentCustomerIdStrippedName] = mySource.[kore_ParentCustomerIdStrippedName]
     ,myTarget.[kore_PrimaryAccountNumber] = mySource.[kore_PrimaryAccountNumber]
     ,myTarget.[kore_TicketingContactType] = mySource.[kore_TicketingContactType]
     ,myTarget.[kore_accountaliasid] = mySource.[kore_accountaliasid]
     ,myTarget.[kore_CheckedOutById] = mySource.[kore_CheckedOutById]
     ,myTarget.[client_BWContactId] = mySource.[client_BWContactId]
     ,myTarget.[kore_BWBaseDate] = mySource.[kore_BWBaseDate]
     ,myTarget.[kore_BWCompanyId] = mySource.[kore_BWCompanyId]
     ,myTarget.[kore_BWContactId] = mySource.[kore_BWContactId]
     ,myTarget.[kore_BWSequence] = mySource.[kore_BWSequence]
     ,myTarget.[cdi_age] = mySource.[cdi_age]
     ,myTarget.[cdi_allowtextmessages] = mySource.[cdi_allowtextmessages]
     ,myTarget.[cdi_facebook] = mySource.[cdi_facebook]
     ,myTarget.[cdi_gender] = mySource.[cdi_gender]
     ,myTarget.[cdi_grade] = mySource.[cdi_grade]
     ,myTarget.[cdi_identifiedon] = mySource.[cdi_identifiedon]
     ,myTarget.[cdi_image] = mySource.[cdi_image]
     ,myTarget.[cdi_ip] = mySource.[cdi_ip]
     ,myTarget.[cdi_latitude] = mySource.[cdi_latitude]
     ,myTarget.[cdi_linkedin] = mySource.[cdi_linkedin]
     ,myTarget.[cdi_Longitude] = mySource.[cdi_Longitude]
     ,myTarget.[cdi_partitionkey] = mySource.[cdi_partitionkey]
     ,myTarget.[cdi_rowkey] = mySource.[cdi_rowkey]
     ,myTarget.[cdi_score] = mySource.[cdi_score]
     ,myTarget.[cdi_social] = mySource.[cdi_social]
     ,myTarget.[cdi_totalscore] = mySource.[cdi_totalscore]
     ,myTarget.[cdi_twitter] = mySource.[cdi_twitter]
     ,myTarget.[cdi_visitorkey] = mySource.[cdi_visitorkey]
     ,myTarget.[new_DomeAccountNumber] = mySource.[new_DomeAccountNumber]
     ,myTarget.[new_DomeContractStart] = mySource.[new_DomeContractStart]
     ,myTarget.[new_DomeContractEnd] = mySource.[new_DomeContractEnd]
     ,myTarget.[new_DomeContractExt] = mySource.[new_DomeContractExt]
     ,myTarget.[new_DomeContractEscalator] = mySource.[new_DomeContractEscalator]
     ,myTarget.[new_DomeSeats] = mySource.[new_DomeSeats]
     ,myTarget.[new_somethingelse] = mySource.[new_somethingelse]
     ,myTarget.[new_ImportSource] = mySource.[new_ImportSource]
     ,myTarget.[new_MyFinder] = mySource.[new_MyFinder]
     ,myTarget.[new_GeorgiaDomeSeats] = mySource.[new_GeorgiaDomeSeats]
     ,myTarget.[new_Source] = mySource.[new_Source]
     ,myTarget.[new_Subscription_EReport] = mySource.[new_Subscription_EReport]
     ,myTarget.[new_Subscription_Postgame_STH] = mySource.[new_Subscription_Postgame_STH]
     ,myTarget.[new_Subscription_Pregame_STH] = mySource.[new_Subscription_Pregame_STH]
     ,myTarget.[new_Subscription_GearMail] = mySource.[new_Subscription_GearMail]
     ,myTarget.[new_Subscription_TicketSuiteSales] = mySource.[new_Subscription_TicketSuiteSales]
     ,myTarget.[new_Subscription_PreferredPartner] = mySource.[new_Subscription_PreferredPartner]
     ,myTarget.[new_Subscription_Ticket_Offers] = mySource.[new_Subscription_Ticket_Offers]
     ,myTarget.[kore_InvoiceBalance] = mySource.[kore_InvoiceBalance]
     ,myTarget.[kore_invoicebalance_Base] = mySource.[kore_invoicebalance_Base]
     ,myTarget.[kore_SinceDate] = mySource.[kore_SinceDate]
     ,myTarget.[new_PIF_Amount] = mySource.[new_PIF_Amount]
     ,myTarget.[new_pif_amount_Base] = mySource.[new_pif_amount_Base]
     ,myTarget.[new_5MonthlyPaymentAmt] = mySource.[new_5MonthlyPaymentAmt]
     ,myTarget.[new_5monthlypaymentamt_Base] = mySource.[new_5monthlypaymentamt_Base]
     ,myTarget.[new_40_60PaymentAmt] = mySource.[new_40_60PaymentAmt]
     ,myTarget.[new_40_60paymentamt_Base] = mySource.[new_40_60paymentamt_Base]
     ,myTarget.[new_PersonalURL] = mySource.[new_PersonalURL]
     ,myTarget.[new_FavoritePlayer] = mySource.[new_FavoritePlayer]
     ,myTarget.[new_RelocationDateTime] = mySource.[new_RelocationDateTime]
     ,myTarget.[new_NFLAccount] = mySource.[new_NFLAccount]
     ,myTarget.[new_NFLAccountPassword] = mySource.[new_NFLAccountPassword]
     ,myTarget.[new_CurrentSeasonAccountHolder] = mySource.[new_CurrentSeasonAccountHolder]
     ,myTarget.[new_Subscription_MLSSubscription] = mySource.[new_Subscription_MLSSubscription]
     ,myTarget.[new_new_subscription_MLSOfficialGearMail] = mySource.[new_new_subscription_MLSOfficialGearMail]
     ,myTarget.[new_Address1_MetroArea] = mySource.[new_Address1_MetroArea]
     ,myTarget.[new_NFLMC1] = mySource.[new_NFLMC1]
     ,myTarget.[new_NFLMCCode1] = mySource.[new_NFLMCCode1]
     ,myTarget.[new_NFLMCURL2] = mySource.[new_NFLMCURL2]
     ,myTarget.[new_NFLMCCode2] = mySource.[new_NFLMCCode2]
     ,myTarget.[new_NFLMCCode3] = mySource.[new_NFLMCCode3]
     ,myTarget.[new_NFLMCCode4] = mySource.[new_NFLMCCode4]
     ,myTarget.[new_CurrentSpend] = mySource.[new_CurrentSpend]
     ,myTarget.[new_NSWaitlistConfirmed] = mySource.[new_NSWaitlistConfirmed]
     ,myTarget.[kore_archticsids] = mySource.[kore_archticsids]
     ,myTarget.[kore_ExternalContactId] = mySource.[kore_ExternalContactId]
     ,myTarget.[kore_GroupBuyer] = mySource.[kore_GroupBuyer]
     ,myTarget.[kore_GroupCategory] = mySource.[kore_GroupCategory]
     ,myTarget.[kore_HeritageNationality] = mySource.[kore_HeritageNationality]
     ,myTarget.[kore_MilesFromFacility] = mySource.[kore_MilesFromFacility]
     ,myTarget.[kore_MiniPlanHolder] = mySource.[kore_MiniPlanHolder]
     ,myTarget.[kore_OverrideCheckoutExpiration] = mySource.[kore_OverrideCheckoutExpiration]
     ,myTarget.[kore_PrimaryArchticsId] = mySource.[kore_PrimaryArchticsId]
     ,myTarget.[kore_SeasonTicketHolder] = mySource.[kore_SeasonTicketHolder]
     ,myTarget.[kore_SecondaryArchticsName] = mySource.[kore_SecondaryArchticsName]
     ,myTarget.[kore_SecondaryEmail] = mySource.[kore_SecondaryEmail]
     ,myTarget.[kore_SuiteBuyer] = mySource.[kore_SuiteBuyer]
     ,myTarget.[kore_GroupSalesRep] = mySource.[kore_GroupSalesRep]
     ,myTarget.[kore_SuiteSalesRep] = mySource.[kore_SuiteSalesRep]
     ,myTarget.[kore_TicketingSalesRep] = mySource.[kore_TicketingSalesRep]
     ,myTarget.[kore_TicketingServiceRep] = mySource.[kore_TicketingServiceRep]
     ,myTarget.[li_CompanyId] = mySource.[li_CompanyId]
     ,myTarget.[li_MemberToken] = mySource.[li_MemberToken]
     ,myTarget.[new_SponsorshipCheckedOutBy] = mySource.[new_SponsorshipCheckedOutBy]
     ,myTarget.[new_SponsorshipCheckedOutUntil] = mySource.[new_SponsorshipCheckedOutUntil]
     ,myTarget.[new_NSCheckedOutBy] = mySource.[new_NSCheckedOutBy]
     ,myTarget.[new_NSCheckedOutUntil] = mySource.[new_NSCheckedOutUntil]
     ,myTarget.[new_AMBFFNewsletter] = mySource.[new_AMBFFNewsletter]
     ,myTarget.[new_AFYFNetwork] = mySource.[new_AFYFNetwork]
     ,myTarget.[new_WNPFNetwork] = mySource.[new_WNPFNetwork]
     ,myTarget.[new_AmericanExplorers] = mySource.[new_AmericanExplorers]
     ,myTarget.[new_AMBFFTrustees] = mySource.[new_AMBFFTrustees]
     ,myTarget.[KORE_IsBillingContact] = mySource.[KORE_IsBillingContact]
     ,myTarget.[KORE_IsPrimaryContact] = mySource.[KORE_IsPrimaryContact]
     ,myTarget.[KORE_sponsoraccountnumber] = mySource.[KORE_sponsoraccountnumber]
     ,myTarget.[new_NSReservationDate] = mySource.[new_NSReservationDate]
     ,myTarget.[client_gpaccountnumber] = mySource.[client_gpaccountnumber]
     ,myTarget.[client_GPCustomerClass] = mySource.[client_GPCustomerClass]
     ,myTarget.[client_triggergp] = mySource.[client_triggergp]
     ,myTarget.[new_NSAppointmentIdentifier] = mySource.[new_NSAppointmentIdentifier]
     ,myTarget.[new_NSPURL] = mySource.[new_NSPURL]
     ,myTarget.[new_NSPasscode] = mySource.[new_NSPasscode]
     ,myTarget.[new_NSRepEmail] = mySource.[new_NSRepEmail]
     ,myTarget.[new_NSRepPhone] = mySource.[new_NSRepPhone]
     ,myTarget.[new_MLSFoundersSurveyLink] = mySource.[new_MLSFoundersSurveyLink]
     ,myTarget.[new_NSLicenseeName] = mySource.[new_NSLicenseeName]
     ,myTarget.[new_FoundationSubscription] = mySource.[new_FoundationSubscription]
     ,myTarget.[new_FuturePhaseRep] = mySource.[new_FuturePhaseRep]
     ,myTarget.[new_FuturePhaseNotes] = mySource.[new_FuturePhaseNotes]
     ,myTarget.[new_subscriptionNewStadiumInformationOffers] = mySource.[new_subscriptionNewStadiumInformationOffers]
     ,myTarget.[new_AllocatedSeatLocation] = mySource.[new_AllocatedSeatLocation]
     ,myTarget.[new_VirtualseatView] = mySource.[new_VirtualseatView]
     ,myTarget.[new_MLSLiveCode] = mySource.[new_MLSLiveCode]
     ,myTarget.[new_NSReserveSeatInterest] = mySource.[new_NSReserveSeatInterest]
     ,myTarget.[new_NSClubSeatInterest] = mySource.[new_NSClubSeatInterest]
     ,myTarget.[new_NSReserveInterest] = mySource.[new_NSReserveInterest]
     ,myTarget.[new_NSClubInterest] = mySource.[new_NSClubInterest]
     ,myTarget.[new_NSSuiteInterest] = mySource.[new_NSSuiteInterest]
     ,myTarget.[new_BrokerFlag] = mySource.[new_BrokerFlag]
     ,myTarget.[new_FalconsNASSurveyLink] = mySource.[new_FalconsNASSurveyLink]
     ,myTarget.[new_TypeOfGroup] = mySource.[new_TypeOfGroup]
     ,myTarget.[new_MiscField] = mySource.[new_MiscField]
     ,myTarget.[new_InterestType] = mySource.[new_InterestType]
     ,myTarget.[new_NumberofSeats] = mySource.[new_NumberofSeats]
     ,myTarget.[new_InterestLevel] = mySource.[new_InterestLevel]
     ,myTarget.[new_SeatingPreference] = mySource.[new_SeatingPreference]
     ,myTarget.[new_NumberofTickets] = mySource.[new_NumberofTickets]
     ,myTarget.[new_AtlantaUnitedFCMajorLeagueSoccer] = mySource.[new_AtlantaUnitedFCMajorLeagueSoccer]
     ,myTarget.[new_AtlantaUnitedFCEventsFanPerksa] = mySource.[new_AtlantaUnitedFCEventsFanPerksa]
     ,myTarget.[new_AtlantaFalconsNationalFootballLeague] = mySource.[new_AtlantaFalconsNationalFootballLeague]
     ,myTarget.[new_FanCouncilURL] = mySource.[new_FanCouncilURL]
     ,myTarget.[new_MemoriesStartingCredits] = mySource.[new_MemoriesStartingCredits]
     ,myTarget.[new_MemoriesRedeemedCredits] = mySource.[new_MemoriesRedeemedCredits]
     ,myTarget.[new_MemoriesRemainingCredits] = mySource.[new_MemoriesRemainingCredits]
     ,myTarget.[new_MemoriesLastUpdated] = mySource.[new_MemoriesLastUpdated]
     ,myTarget.[new_MemoriesRegisteredMember] = mySource.[new_MemoriesRegisteredMember]
     ,myTarget.[new_PSLAcctMgrPIN] = mySource.[new_PSLAcctMgrPIN]
     ,myTarget.[new_TETicketsPurchased] = mySource.[new_TETicketsPurchased]
     ,myTarget.[new_TEGamesPurchased] = mySource.[new_TEGamesPurchased]
     ,myTarget.[new_TEMoneySpent] = mySource.[new_TEMoneySpent]
     ,myTarget.[new_temoneyspent_Base] = mySource.[new_temoneyspent_Base]
     ,myTarget.[new_ExcludeFromMBSEmails] = mySource.[new_ExcludeFromMBSEmails]
     ,myTarget.[new_SGBGamesPurchased] = mySource.[new_SGBGamesPurchased]
     ,myTarget.[new_SGBTicketsPurchased] = mySource.[new_SGBTicketsPurchased]
     ,myTarget.[new_SGBMoneySpent] = mySource.[new_SGBMoneySpent]
     ,myTarget.[new_sgbmoneyspent_Base] = mySource.[new_sgbmoneyspent_Base]
     ,myTarget.[new_ATLUTDSeasonTickets] = mySource.[new_ATLUTDSeasonTickets]
     ,myTarget.[new_ATLUTDGroupTickets] = mySource.[new_ATLUTDGroupTickets]
     ,myTarget.[new_ATLUTDSingleGameTickets] = mySource.[new_ATLUTDSingleGameTickets]
     ,myTarget.[new_TopContact] = mySource.[new_TopContact]
     
WHEN NOT MATCHED BY TARGET
THEN INSERT
     ([ETL_CreatedDate]
     ,[ETL_UpdatedDate]
     ,[ETL_IsDeleted]
     ,[ETL_DeletedDate]
     ,[ETL_DeltaHashKey]
     ,[ContactId]
     ,[KORE_address1_telephone1dncstatus]
     ,[KORE_address1_telephone2dncstatus]
     ,[KORE_address1_telephone3dncstatus]
     ,[kore_address1milesfromfacility]
     ,[KORE_address2_telephone1dncstatus]
     ,[KORE_address2_telephone2dncstatus]
     ,[KORE_address2_telephone3dncstatus]
     ,[KORE_assistantphonedncstatus]
     ,[KORE_AttentionName]
     ,[KORE_ImportID]
     ,[KORE_LastContacted]
     ,[KORE_LastSync]
     ,[KORE_ListAttributeName]
     ,[KORE_ListAttributeValue]
     ,[KORE_managerphonedncstatus]
     ,[KORE_mobilephonedncstatus]
     ,[KORE_SeniorityDate]
     ,[KORE_telephone1DNCStatus]
     ,[KORE_telephone1dncstatustype]
     ,[KORE_telephone2dncstatus]
     ,[KORE_telephone2dncstatustype]
     ,[KORE_telephone3dncstatus]
     ,[KORE_telephone3dncstatustype]
     ,[KORE_Type]
     ,[kore_countryid]
     ,[kore_stateorprovinceid]
     ,[kore_sourcemarketinglistid]
     ,[kore_lastcontactedbyid]
     ,[kore_AccountNumbers]
     ,[kore_CheckedOutUntil]
     ,[kore_CompanyName]
     ,[kore_OptOutOfDuplicateDetection]
     ,[kore_ParentCustomerIdStrippedName]
     ,[kore_PrimaryAccountNumber]
     ,[kore_TicketingContactType]
     ,[kore_accountaliasid]
     ,[kore_CheckedOutById]
     ,[client_BWContactId]
     ,[kore_BWBaseDate]
     ,[kore_BWCompanyId]
     ,[kore_BWContactId]
     ,[kore_BWSequence]
     ,[cdi_age]
     ,[cdi_allowtextmessages]
     ,[cdi_facebook]
     ,[cdi_gender]
     ,[cdi_grade]
     ,[cdi_identifiedon]
     ,[cdi_image]
     ,[cdi_ip]
     ,[cdi_latitude]
     ,[cdi_linkedin]
     ,[cdi_Longitude]
     ,[cdi_partitionkey]
     ,[cdi_rowkey]
     ,[cdi_score]
     ,[cdi_social]
     ,[cdi_totalscore]
     ,[cdi_twitter]
     ,[cdi_visitorkey]
     ,[new_DomeAccountNumber]
     ,[new_DomeContractStart]
     ,[new_DomeContractEnd]
     ,[new_DomeContractExt]
     ,[new_DomeContractEscalator]
     ,[new_DomeSeats]
     ,[new_somethingelse]
     ,[new_ImportSource]
     ,[new_MyFinder]
     ,[new_GeorgiaDomeSeats]
     ,[new_Source]
     ,[new_Subscription_EReport]
     ,[new_Subscription_Postgame_STH]
     ,[new_Subscription_Pregame_STH]
     ,[new_Subscription_GearMail]
     ,[new_Subscription_TicketSuiteSales]
     ,[new_Subscription_PreferredPartner]
     ,[new_Subscription_Ticket_Offers]
     ,[kore_InvoiceBalance]
     ,[kore_invoicebalance_Base]
     ,[kore_SinceDate]
     ,[new_PIF_Amount]
     ,[new_pif_amount_Base]
     ,[new_5MonthlyPaymentAmt]
     ,[new_5monthlypaymentamt_Base]
     ,[new_40_60PaymentAmt]
     ,[new_40_60paymentamt_Base]
     ,[new_PersonalURL]
     ,[new_FavoritePlayer]
     ,[new_RelocationDateTime]
     ,[new_NFLAccount]
     ,[new_NFLAccountPassword]
     ,[new_CurrentSeasonAccountHolder]
     ,[new_Subscription_MLSSubscription]
     ,[new_new_subscription_MLSOfficialGearMail]
     ,[new_Address1_MetroArea]
     ,[new_NFLMC1]
     ,[new_NFLMCCode1]
     ,[new_NFLMCURL2]
     ,[new_NFLMCCode2]
     ,[new_NFLMCCode3]
     ,[new_NFLMCCode4]
     ,[new_CurrentSpend]
     ,[new_NSWaitlistConfirmed]
     ,[kore_archticsids]
     ,[kore_ExternalContactId]
     ,[kore_GroupBuyer]
     ,[kore_GroupCategory]
     ,[kore_HeritageNationality]
     ,[kore_MilesFromFacility]
     ,[kore_MiniPlanHolder]
     ,[kore_OverrideCheckoutExpiration]
     ,[kore_PrimaryArchticsId]
     ,[kore_SeasonTicketHolder]
     ,[kore_SecondaryArchticsName]
     ,[kore_SecondaryEmail]
     ,[kore_SuiteBuyer]
     ,[kore_GroupSalesRep]
     ,[kore_SuiteSalesRep]
     ,[kore_TicketingSalesRep]
     ,[kore_TicketingServiceRep]
     ,[li_CompanyId]
     ,[li_MemberToken]
     ,[new_SponsorshipCheckedOutBy]
     ,[new_SponsorshipCheckedOutUntil]
     ,[new_NSCheckedOutBy]
     ,[new_NSCheckedOutUntil]
     ,[new_AMBFFNewsletter]
     ,[new_AFYFNetwork]
     ,[new_WNPFNetwork]
     ,[new_AmericanExplorers]
     ,[new_AMBFFTrustees]
     ,[KORE_IsBillingContact]
     ,[KORE_IsPrimaryContact]
     ,[KORE_sponsoraccountnumber]
     ,[new_NSReservationDate]
     ,[client_gpaccountnumber]
     ,[client_GPCustomerClass]
     ,[client_triggergp]
     ,[new_NSAppointmentIdentifier]
     ,[new_NSPURL]
     ,[new_NSPasscode]
     ,[new_NSRepEmail]
     ,[new_NSRepPhone]
     ,[new_MLSFoundersSurveyLink]
     ,[new_NSLicenseeName]
     ,[new_FoundationSubscription]
     ,[new_FuturePhaseRep]
     ,[new_FuturePhaseNotes]
     ,[new_subscriptionNewStadiumInformationOffers]
     ,[new_AllocatedSeatLocation]
     ,[new_VirtualseatView]
     ,[new_MLSLiveCode]
     ,[new_NSReserveSeatInterest]
     ,[new_NSClubSeatInterest]
     ,[new_NSReserveInterest]
     ,[new_NSClubInterest]
     ,[new_NSSuiteInterest]
     ,[new_BrokerFlag]
     ,[new_FalconsNASSurveyLink]
     ,[new_TypeOfGroup]
     ,[new_MiscField]
     ,[new_InterestType]
     ,[new_NumberofSeats]
     ,[new_InterestLevel]
     ,[new_SeatingPreference]
     ,[new_NumberofTickets]
     ,[new_AtlantaUnitedFCMajorLeagueSoccer]
     ,[new_AtlantaUnitedFCEventsFanPerksa]
     ,[new_AtlantaFalconsNationalFootballLeague]
     ,[new_FanCouncilURL]
     ,[new_MemoriesStartingCredits]
     ,[new_MemoriesRedeemedCredits]
     ,[new_MemoriesRemainingCredits]
     ,[new_MemoriesLastUpdated]
     ,[new_MemoriesRegisteredMember]
     ,[new_PSLAcctMgrPIN]
     ,[new_TETicketsPurchased]
     ,[new_TEGamesPurchased]
     ,[new_TEMoneySpent]
     ,[new_temoneyspent_Base]
     ,[new_ExcludeFromMBSEmails]
     ,[new_SGBGamesPurchased]
     ,[new_SGBTicketsPurchased]
     ,[new_SGBMoneySpent]
     ,[new_sgbmoneyspent_Base]
     ,[new_ATLUTDSeasonTickets]
     ,[new_ATLUTDGroupTickets]
     ,[new_ATLUTDSingleGameTickets]
     ,[new_TopContact]
     )
VALUES
     (@RunTime --ETL_CreatedDate
     ,@RunTime --ETL_UpdateddDate
     ,0 --ETL_DeletedDate
     ,NULL --ETL_DeletedDate
     ,mySource.[ETL_DeltaHashKey]
     ,mySource.[ContactId]
     ,mySource.[KORE_address1_telephone1dncstatus]
     ,mySource.[KORE_address1_telephone2dncstatus]
     ,mySource.[KORE_address1_telephone3dncstatus]
     ,mySource.[kore_address1milesfromfacility]
     ,mySource.[KORE_address2_telephone1dncstatus]
     ,mySource.[KORE_address2_telephone2dncstatus]
     ,mySource.[KORE_address2_telephone3dncstatus]
     ,mySource.[KORE_assistantphonedncstatus]
     ,mySource.[KORE_AttentionName]
     ,mySource.[KORE_ImportID]
     ,mySource.[KORE_LastContacted]
     ,mySource.[KORE_LastSync]
     ,mySource.[KORE_ListAttributeName]
     ,mySource.[KORE_ListAttributeValue]
     ,mySource.[KORE_managerphonedncstatus]
     ,mySource.[KORE_mobilephonedncstatus]
     ,mySource.[KORE_SeniorityDate]
     ,mySource.[KORE_telephone1DNCStatus]
     ,mySource.[KORE_telephone1dncstatustype]
     ,mySource.[KORE_telephone2dncstatus]
     ,mySource.[KORE_telephone2dncstatustype]
     ,mySource.[KORE_telephone3dncstatus]
     ,mySource.[KORE_telephone3dncstatustype]
     ,mySource.[KORE_Type]
     ,mySource.[kore_countryid]
     ,mySource.[kore_stateorprovinceid]
     ,mySource.[kore_sourcemarketinglistid]
     ,mySource.[kore_lastcontactedbyid]
     ,mySource.[kore_AccountNumbers]
     ,mySource.[kore_CheckedOutUntil]
     ,mySource.[kore_CompanyName]
     ,mySource.[kore_OptOutOfDuplicateDetection]
     ,mySource.[kore_ParentCustomerIdStrippedName]
     ,mySource.[kore_PrimaryAccountNumber]
     ,mySource.[kore_TicketingContactType]
     ,mySource.[kore_accountaliasid]
     ,mySource.[kore_CheckedOutById]
     ,mySource.[client_BWContactId]
     ,mySource.[kore_BWBaseDate]
     ,mySource.[kore_BWCompanyId]
     ,mySource.[kore_BWContactId]
     ,mySource.[kore_BWSequence]
     ,mySource.[cdi_age]
     ,mySource.[cdi_allowtextmessages]
     ,mySource.[cdi_facebook]
     ,mySource.[cdi_gender]
     ,mySource.[cdi_grade]
     ,mySource.[cdi_identifiedon]
     ,mySource.[cdi_image]
     ,mySource.[cdi_ip]
     ,mySource.[cdi_latitude]
     ,mySource.[cdi_linkedin]
     ,mySource.[cdi_Longitude]
     ,mySource.[cdi_partitionkey]
     ,mySource.[cdi_rowkey]
     ,mySource.[cdi_score]
     ,mySource.[cdi_social]
     ,mySource.[cdi_totalscore]
     ,mySource.[cdi_twitter]
     ,mySource.[cdi_visitorkey]
     ,mySource.[new_DomeAccountNumber]
     ,mySource.[new_DomeContractStart]
     ,mySource.[new_DomeContractEnd]
     ,mySource.[new_DomeContractExt]
     ,mySource.[new_DomeContractEscalator]
     ,mySource.[new_DomeSeats]
     ,mySource.[new_somethingelse]
     ,mySource.[new_ImportSource]
     ,mySource.[new_MyFinder]
     ,mySource.[new_GeorgiaDomeSeats]
     ,mySource.[new_Source]
     ,mySource.[new_Subscription_EReport]
     ,mySource.[new_Subscription_Postgame_STH]
     ,mySource.[new_Subscription_Pregame_STH]
     ,mySource.[new_Subscription_GearMail]
     ,mySource.[new_Subscription_TicketSuiteSales]
     ,mySource.[new_Subscription_PreferredPartner]
     ,mySource.[new_Subscription_Ticket_Offers]
     ,mySource.[kore_InvoiceBalance]
     ,mySource.[kore_invoicebalance_Base]
     ,mySource.[kore_SinceDate]
     ,mySource.[new_PIF_Amount]
     ,mySource.[new_pif_amount_Base]
     ,mySource.[new_5MonthlyPaymentAmt]
     ,mySource.[new_5monthlypaymentamt_Base]
     ,mySource.[new_40_60PaymentAmt]
     ,mySource.[new_40_60paymentamt_Base]
     ,mySource.[new_PersonalURL]
     ,mySource.[new_FavoritePlayer]
     ,mySource.[new_RelocationDateTime]
     ,mySource.[new_NFLAccount]
     ,mySource.[new_NFLAccountPassword]
     ,mySource.[new_CurrentSeasonAccountHolder]
     ,mySource.[new_Subscription_MLSSubscription]
     ,mySource.[new_new_subscription_MLSOfficialGearMail]
     ,mySource.[new_Address1_MetroArea]
     ,mySource.[new_NFLMC1]
     ,mySource.[new_NFLMCCode1]
     ,mySource.[new_NFLMCURL2]
     ,mySource.[new_NFLMCCode2]
     ,mySource.[new_NFLMCCode3]
     ,mySource.[new_NFLMCCode4]
     ,mySource.[new_CurrentSpend]
     ,mySource.[new_NSWaitlistConfirmed]
     ,mySource.[kore_archticsids]
     ,mySource.[kore_ExternalContactId]
     ,mySource.[kore_GroupBuyer]
     ,mySource.[kore_GroupCategory]
     ,mySource.[kore_HeritageNationality]
     ,mySource.[kore_MilesFromFacility]
     ,mySource.[kore_MiniPlanHolder]
     ,mySource.[kore_OverrideCheckoutExpiration]
     ,mySource.[kore_PrimaryArchticsId]
     ,mySource.[kore_SeasonTicketHolder]
     ,mySource.[kore_SecondaryArchticsName]
     ,mySource.[kore_SecondaryEmail]
     ,mySource.[kore_SuiteBuyer]
     ,mySource.[kore_GroupSalesRep]
     ,mySource.[kore_SuiteSalesRep]
     ,mySource.[kore_TicketingSalesRep]
     ,mySource.[kore_TicketingServiceRep]
     ,mySource.[li_CompanyId]
     ,mySource.[li_MemberToken]
     ,mySource.[new_SponsorshipCheckedOutBy]
     ,mySource.[new_SponsorshipCheckedOutUntil]
     ,mySource.[new_NSCheckedOutBy]
     ,mySource.[new_NSCheckedOutUntil]
     ,mySource.[new_AMBFFNewsletter]
     ,mySource.[new_AFYFNetwork]
     ,mySource.[new_WNPFNetwork]
     ,mySource.[new_AmericanExplorers]
     ,mySource.[new_AMBFFTrustees]
     ,mySource.[KORE_IsBillingContact]
     ,mySource.[KORE_IsPrimaryContact]
     ,mySource.[KORE_sponsoraccountnumber]
     ,mySource.[new_NSReservationDate]
     ,mySource.[client_gpaccountnumber]
     ,mySource.[client_GPCustomerClass]
     ,mySource.[client_triggergp]
     ,mySource.[new_NSAppointmentIdentifier]
     ,mySource.[new_NSPURL]
     ,mySource.[new_NSPasscode]
     ,mySource.[new_NSRepEmail]
     ,mySource.[new_NSRepPhone]
     ,mySource.[new_MLSFoundersSurveyLink]
     ,mySource.[new_NSLicenseeName]
	 ,mysource.[new_FoundationSubscription]
     ,mysource.[new_FuturePhaseRep]
     ,mysource.[new_FuturePhaseNotes]
     ,mysource.[new_subscriptionNewStadiumInformationOffers]
     ,mysource.[new_AllocatedSeatLocation]
     ,mysource.[new_VirtualseatView]
     ,mysource.[new_MLSLiveCode]
     ,mysource.[new_NSReserveSeatInterest]
     ,mysource.[new_NSClubSeatInterest]
     ,mysource.[new_NSReserveInterest]
     ,mysource.[new_NSClubInterest]
     ,mysource.[new_NSSuiteInterest]
     ,mysource.[new_BrokerFlag]
     ,mysource.[new_FalconsNASSurveyLink]
     ,mysource.[new_TypeOfGroup]
     ,mysource.[new_MiscField]
     ,mysource.[new_InterestType]
     ,mysource.[new_NumberofSeats]
     ,mysource.[new_InterestLevel]
     ,mysource.[new_SeatingPreference]
     ,mysource.[new_NumberofTickets]
     ,mysource.[new_AtlantaUnitedFCMajorLeagueSoccer]
     ,mysource.[new_AtlantaUnitedFCEventsFanPerksa]
     ,mysource.[new_AtlantaFalconsNationalFootballLeague]
     ,mysource.[new_FanCouncilURL]
     ,mysource.[new_MemoriesStartingCredits]
     ,mysource.[new_MemoriesRedeemedCredits]
     ,mysource.[new_MemoriesRemainingCredits]
     ,mysource.[new_MemoriesLastUpdated]
     ,mysource.[new_MemoriesRegisteredMember]
     ,mysource.[new_PSLAcctMgrPIN]
     ,mysource.[new_TETicketsPurchased]
     ,mysource.[new_TEGamesPurchased]
     ,mysource.[new_TEMoneySpent]
     ,mysource.[new_temoneyspent_Base]
     ,mysource.[new_ExcludeFromMBSEmails]
     ,mysource.[new_SGBGamesPurchased]
     ,mysource.[new_SGBTicketsPurchased]
     ,mysource.[new_SGBMoneySpent]
     ,mysource.[new_sgbmoneyspent_Base]
     ,mysource.[new_ATLUTDSeasonTickets]
     ,mysource.[new_ATLUTDGroupTickets]
     ,mysource.[new_ATLUTDSingleGameTickets]
     ,mysource.[new_TopContact]

       )
;



DECLARE @MergeInsertRowCount int = ISNULL((SELECT CONVERT(varchar, COUNT(*)) FROM ProdCopy.ContactExtensionBase WHERE ETL_CreatedDate >= @RunTime AND ETL_UpdatedDate = ETL_CreatedDate),'0');	
DECLARE @MergeUpdateRowCount int = ISNULL((SELECT CONVERT(varchar, COUNT(*)) FROM ProdCopy.ContactExtensionBase WHERE ETL_UpdatedDate >= @RunTime AND ETL_UpdatedDate > ETL_CreatedDate),'0');	


END TRY 
BEGIN CATCH 

	DECLARE @ErrorMessage nvarchar(4000) = ERROR_MESSAGE();
	DECLARE @ErrorSeverity INT = ERROR_SEVERITY();
	DECLARE @ErrorState INT = ERROR_STATE();
			
	PRINT @ErrorMessage

	RAISERROR (@ErrorMessage, @ErrorSeverity, @ErrorState)

END CATCH


END
    
GO
