CREATE TABLE [archive].[IMC_MasterDB_20170619]
(
[RECIPIENT_ID] [varchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Email] [varchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Opt In Date] [varchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Opted Out] [varchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Opt In Details] [varchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Email Type] [varchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Opted Out Date] [varchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Opt Out Details] [varchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CRM Lead Source] [varchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CRM Sync ID] [varchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CRM Enable Sync] [varchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CRM Contact Type] [varchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CRM Account ID] [varchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Last Modified Date] [varchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[2016 PSL Payment Paid] [varchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[2017 PSL Amount Due] [varchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[2017 PSL Payment Paid] [varchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[21 or older] [varchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AF Season Schedule] [varchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AF Ticket Offers] [varchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AUExclusiveContentNotifications] [varchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AUInTheStadiumNotifications] [varchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AUMatchStartNotifications] [varchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AUParkingAndTransitNotifications] [varchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AUScoringNotifications] [varchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AUTeamNewsNotifications] [varchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Academy Team] [varchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Academy Tried Out] [varchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Additional Comments] [varchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Address1_City] [varchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Address1_Country] [varchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Address1_County] [varchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Address1_Line1] [varchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Address1_Line2] [varchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Address1_Line3] [varchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Address1_PostalCode] [varchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Address1_StateOrProvince] [varchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Agree Official Rules] [varchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AllowSMS] [varchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Appointment Time] [varchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AssistantName] [varchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AssistantPhone] [varchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Associated Archtics ID Suite Owner Admin] [varchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BirthDate] [varchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CRM Sync ID 2] [varchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CRM_Contact_ID] [varchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Company] [varchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Corporate Client or Employee Entertainment] [varchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Corporate Entertainment] [varchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Current Stadium Employee] [varchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DoNotBulkEMail] [varchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DoNotBulkPostalMail] [varchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DoNotEMail] [varchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DoNotPostalMail] [varchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Duplicate] [varchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Executive Member] [varchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Falcons Group] [varchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Falcons Home Opponents] [varchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Falcons Insider] [varchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Falcons SGB TE TF] [varchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Falcons Season Ticket Holder] [varchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Falcons Season Tix Due] [varchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Falcons Seating Preference] [varchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FirstName] [varchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Founding Members no seats] [varchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Founding Members with seats] [varchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FullName] [varchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[GA Dome Premium Events] [varchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[GA Dome Seating Preferences] [varchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[GenderCode] [varchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Group Size] [varchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Group Type] [varchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[HasChildrenCode] [varchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[JobTitle] [varchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[KIA Account] [varchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[KORE_Type] [varchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LastName] [varchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Last_Click] [varchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Last_Open] [varchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Last_Sent] [varchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MBS Events] [varchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MBS Events Stay Informed] [varchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MBS Hiring Emails] [varchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MBS Seating Interest] [varchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MiddleName] [varchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Mobile User Id] [varchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MobilePhone] [varchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[My Finder] [varchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Opt Out of Arthur M Blank Foundation Email Communication] [varchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Opt Out of Atlanta Falcons Email Communication] [varchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Opt Out of Atlanta United Email Communication] [varchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PSL Owner] [varchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Part Time Positions] [varchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Phone Call Opt In] [varchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Playoff Payment] [varchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Preferred Partner] [varchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Preferred Ticket Price] [varchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PreferredLanguage] [varchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Primary Rep] [varchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Primary Rep Email] [varchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Primary Rep Name] [varchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Primary Rep Phone] [varchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Question or Comment] [varchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Salutation] [varchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Seating Level Preference] [varchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Send Hour] [varchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[StateCode] [varchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Suffix] [varchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Team Member Referral] [varchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Team Member Requirements] [varchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Telephone1] [varchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Telephone2] [varchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[UTD Acct Number] [varchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[UTD Event Sign Up] [varchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[UTD Group] [varchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[UTD Group  Type] [varchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[UTD Group Size] [varchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[UTD Home Opponents] [varchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[UTD Multi Game] [varchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[UTD SGB TE TF] [varchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[UTD Season Schedule] [varchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[UTD Season Tix Due] [varchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[UTD Seating Preferences] [varchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[UTD Test_Behavior] [varchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[UTD Test_Rank] [varchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[UTD Test_Score] [varchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[United Season Ticket Holder] [varchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[United Seating Preference] [varchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[UnitedStayConnected] [varchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Unsubscribe from CD] [varchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cdi_facebook] [varchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cdi_linkedin] [varchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cdi_twitter] [varchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_BWContactId] [varchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_ambffsuppression] [varchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[kore_BWBaseDate] [varchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[kore_BWCompanyId] [varchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[kore_BWContactId] [varchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[kore_BWSequence] [varchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[kore_CheckedOutById] [varchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[kore_CheckedOutByIdName] [varchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[kore_InvoiceBalance] [varchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[kore_PrimaryAccountNumber] [varchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[kore_SinceDate] [varchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[kore_accountaliasidName] [varchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[kore_address1milesfromfacility] [varchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[new_AFYFNetwork] [varchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[new_AMBFFNewsletter] [varchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[new_AMBFFTrustees] [varchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[new_Address1_MetroArea] [varchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[new_AmericanExplorers] [varchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[new_AtlantaFalconsNationalFootballLeague] [varchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[new_AtlantaUnitedFCEventsFanPerksa] [varchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[new_AtlantaUnitedFCMajorLeagueSoccer] [varchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[new_BrokerFlag] [varchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[new_ExcludeFromMBSEmails] [varchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[new_FalconsNASSurveyLink] [varchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[new_FanCouncilURL] [varchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[new_FoundationSubscription] [varchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[new_HasKidsunder18] [varchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[new_MLSFoundersSurveyLink] [varchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[new_MLSLiveCode] [varchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[new_MemoriesLastUpdated] [varchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[new_MemoriesRedeemedCredits] [varchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[new_MemoriesRegisteredMember] [varchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[new_MemoriesRemainingCredits] [varchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[new_MemoriesStartingCredits] [varchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[new_NFLAccount] [varchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[new_NFLAccountPassword] [varchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[new_NFLMC1] [varchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[new_NFLMCCode1] [varchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[new_NFLMCCode2] [varchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[new_NFLMCCode3] [varchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[new_NFLMCCode4] [varchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[new_NFLMCURL2] [varchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[new_NSCheckedOutBy] [varchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[new_NSCheckedOutByName] [varchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[new_NSLicenseeName] [varchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[new_RelocationDateTime] [varchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[new_SponsorshipCheckedOutBy] [varchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[new_SponsorshipCheckedOutByName] [varchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[new_Subscription_EReport] [varchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[new_Subscription_GearMail] [varchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[new_Subscription_MLSSubscription] [varchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[new_Subscription_Postgame_STH] [varchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[new_Subscription_PreferredPartner] [varchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[new_Subscription_Pregame_STH] [varchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[new_Subscription_TicketSuiteSales] [varchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[new_Subscription_Ticket_Offers] [varchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[new_UnitedCheckedOutBy] [varchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[new_UnitedCheckedOutByName] [varchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[new_VirtualseatView] [varchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[new_WNPFNetwork] [varchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[new_new_subscription_MLSOfficialGearMail] [varchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[new_subscriptionNewStadiumInformationOffers] [varchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
)
GO
