CREATE TABLE [audit].[2017_Matchday_Experience_Mercedes_Benz]
(
[RecordID] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[SurveyName] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[started] [datetime] NULL,
[completed] [datetime] NULL,
[Q1-1-CID] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q12-How Many Regular Season Matches Have you Attended] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q13-1-On which date did you most recently attend] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q14-Which of these best describes your seating location] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q16-1-With whom did you attend the match? - Spouse/partner/significant other] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q16-2-With whom did you attend the match? - Children (under the age of 18)] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q16-3-With whom did you attend the match? - Children (child 18+)] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q16-4-With whom did you attend the match? - Other Family Members] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q16-5-With whom did you attend the match? - Friends] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q16-6-With whom did you attend the match? - Clients] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q16-7-With whom did you attend the match? - Employees or colleagues] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q16-8-With whom did you attend the match? - N/A Attended Alone] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q17-How would you rate your overall matchday experience] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q18-To what extent did your experience meet your expectations] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q19-Based on your experience how likely are you to reccomend attending a game] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q20-Please tell us why you provided your rating in the previous question and what could be done to improve?] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q21-A-1-How would you rate the Experience Arriving] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q21-A-2-How would you rate the Venue safety and security] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q21-A-3-How would you rate the Venue Environment] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q21-A-4-How would you rate the Experience with Matchday staff] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q21-A-5-How would you rate the Experience with menu technology] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q21-A-6-How would you rate the Matchday entertainment experience] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q21-A-7-How would you rate the experience with food and beverage] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q21-A-8-How would you rate the experience leaving the stadium] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q23-How would you arrive] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q24-1-Did you arrive before the match for TAILGATING] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q24-2-Did you arrive before the match for American Family Insurance Fan Village OR Party on the Porch?] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q24-3-Did you arrive before the match for PRE-MATCH WARMUPS] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q24-4-Did you arrive before the match for GATHERING AT BAR/RESTARAUNT] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q24-5-Did you arrive before the match for OTHER] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q24-6-Did you arrive before the match AT ALL] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q25-A-1-How would you rate the Communication about transportation recommendations] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q25-A-2-How would you rate the Affordability of parking] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q25-A-3-How would you rate the Availability of parking] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q25-A-4-How would you rate the Traffic/crowd flow and organization] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q25-A-5-How would you rate the Adequacy of signage directing you] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q25-A-6-How would you rate the Helpfulness of parking lot staff and other staff directing flow] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q25-A-7-How would you rate the OVERALL arrival experience] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q277SPECIFIED-3] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q277-Which MARTA station did you use to depart from the Mercedes-Benz Stadium area?] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q28-A-1-How would you rate the personal safety while outside the stadium] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q28-A-2-How would you rate the Security screening process upon entering the stadium] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q28-A-3-How would you rate the Helpfulness of security staff] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q28-A-4-How would you rate the Feeling of personal safety while the stadium] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q28-A-5-How would you rate the Ability to get in touch with security] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q28-A-6-How would you rate the OVERALL experience with safety and security] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q29-A-1-How would you rate the Availability of staff] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q29-A-2-How would you rate the Helpfulness of staff] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q29-A-3-OVERALL experience with matchday staff] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q31-A-1-How would you rate the Quality of the primary video boards] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q31-A-2-How would you rate the Quality of the mobile app] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q31-A-3-How would you rate the Quality of matchday cellular service] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q31-A-4-How would you rate the Availability and quality of Wi-Fi] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q31-A-5-How would you rate the Clarity and volume of sound system] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q31-A-6-How would you rate the OVERALL experience with venue technology] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q3-1-OID] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q32-A-1-How would you rate the Pre-match entertainment] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q32-A-2-How would you rate the Entertainment during match breaks] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q32-A-3-How would you rate the Crowd energy level] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q32-A-4-How would you rate the Team/fan rituals unique to the club] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q32-A-5-How would you rate the Variety of content shown on primary video board(s)] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q32-A-6-How would you rate the OVERALL matchday entertainment experience] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q33-Did you order food and/or beverages while inside] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q34-A-10-How would you rate the Speed of service] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q34-A-11-How would you rate the Quality of service] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q34-A-12-How would you rate the OVERALL food and beverage experience] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q34-A-1-How would you rate the Variety/selection of food] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q34-A-2-How would you rate the Variety/selection of alcoholic beverages] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q34-A-3-How would you rate the Variety/selection of non-alcoholic beverages] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q34-A-4-How would you rate the Quality of food] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q34-A-5-How would you rate the Quality of alcoholic beverages] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q34-A-6-How would you rate the Quality of non-alcoholic beverages] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q34-A-7-How would you rate the Value for the price of food] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q34-A-8-How would you rate the Value for the price of alcoholic beverages] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q34-A-9-How would you rate the Value for the price of non-alcoholic beverages] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q36-A-1-How would you rate the Ease of departure from parking lot] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q36-A-2-How would you rate the Ease of getting to public transportation] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q36-A-3-How would you rate the Clarity and visibility of signage to exits, freeways, MARTA, etc] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q36-A-4-How would you rate the Helpfulness of staff directing people and vehicles] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q36-A-5-How would you rate the Sense of personal safety while leaving] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q36-A-6-How would you rate the OVERALL experience leaving] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q37-Comments - Areas to Improve] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q38-1-What is your zipcode] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q39-Approximately how far do you live from Mercedes-Benz Stadium] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q40-What is your gender] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q4-1-Venue Name] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q42-1-What is your age] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q43-How many children under the age of 18 currently live in your household] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q44-1-Which of the following categories best describes you? (Select all that apply)] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q44-2-Which of the following categories best describes you? (Select all that apply)] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q44-3-Which of the following categories best describes you? (Select all that apply)] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q44-4-Which of the following categories best describes you? (Select all that apply)] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q44-5-Which of the following categories best describes you? (Select all that apply)] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q44-6-Which of the following categories best describes you? (Select all that apply)] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q44-7-Which of the following categories best describes you? (Select all that apply)] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q45-What is your annual household income before taxes?] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q47-Are you currently an official supporters club member ] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q50-Which of the following statements better explains why you attended this match] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q51-Comments - Doing Well] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q52-Desktop vs. Mobile] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q57-How would you rate the performance of the players and coaches] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q58-Is this the first home match you attended this season] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q5-Organization Name] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q60-How would you rate your overall opinion of Mercedes-Benz Stadium] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q61-Which method of entry did you use to enter the turnstiles] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q62-Which gate did you enter through] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q63-Please tell us anything that can be done to improve your entry and security experience] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q64-1] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q65-League] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q66-Study Type] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q68-How would you rate the process of accessing and scanning your tickets] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q70-10-Select the attributes that you would most associate with the matchday staff] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q70-1-Select the attributes that you would most associate with the matchday staff] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q70-2-Select the attributes that you would most associate with the matchday staff] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q70-3-Select the attributes that you would most associate with the matchday staff] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q70-4-Select the attributes that you would most associate with the matchday staff] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q70-5-Select the attributes that you would most associate with the matchday staff] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q70-6-Select the attributes that you would most associate with the matchday staff] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q70-7-Select the attributes that you would most associate with the matchday staff] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q70-8-Select the attributes that you would most associate with the matchday staff] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q70-9-Select the attributes that you would most associate with the matchday staff] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q71-Please tell us anything that can be done to improve stadium technology] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q72-Please tell us anything that can be done to improve your food and beverage experience] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q73-How did you leave the stadium area?] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q74-Where did you get in your Lyft?] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q75-A-1-How would you rate Navigating inside the stadium] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q75-A-2-How would you rate Seating comfort] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q75-A-3-How would you rate View of the field from your seat] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q75-A-4-How would you rate View of the \"halo\" video board from your seat] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q75-A-5-How would you rate Building temperature] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q75-A-6-How would you rate Cleanliness of concourse areas] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q75-A-7-How would you rate Cleanliness of restrooms] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q75-A-8-How would you rate OVERALL venue environment] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q76-Please tell us any additional detail on the above aspects] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q77-Do you believe that a loud energetic crowd can help create homefield advantage] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q79-Do you believe fans standing most/all the match helps to add energy and excitement?] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q7-Ticket Type] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q80-Do you believe fans chanting, singing, and cheering help to add energy and excitement?] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q82-A-2-How IMPORTANT do you consider VENUE SAFETY as part of the matchday experience?] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q82-A-3-How IMPORTANT do you consider VENUE ENVIRONMENT as part of the matchday experience?] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q82-A-5-How IMPORTANT do you consider ENTERTAINMENT EXPERIENCE WITH TECHNOLOGY as part of the matchday experience?] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q82-A-6-How IMPORTANT do you consider EXPERIENCE WITH F&B as part of the matchday experience?] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q82-A-7-How IMPORTANT do you consider EXPERIENCE LEAVING as part of the matchday experience?] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q82-A-8] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q83-At the match which best describes your section] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q84-If such an option were available, which best describes your preference] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q87-What is your opinion of the no-smoking policy at Mercedes-Benz Stadium] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q88-Do you have additional feedback for no smoking policy] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q89-Did you visit an official team store or stand/kiosk at the most recent home match] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q90-A-1] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q90-A-2] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q90-A-3] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q90-A-4] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q90-A-5] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q91-Please tell us anything that can be done to improve the merchandise experience] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q92-A-1-When thinking about the <u>content on the video boards, how would you rate the Highlights and replays] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q92-A-2-When thinking about the <u>content on the video boards, how would you rate the In-game stats and information] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q92-A-3-When thinking about the <u>content on the video boards, how would you rate the Ability to see the score] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q92-A-4-When thinking about the <u>content on the video boards, how would you rate the Game clock] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q92-A-5-When thinking about the <u>content on the video boards, how would you rate the Social media content] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q94-A-1-Thinking about your merchandise experience, how would you rate the Variety] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q94-A-2-Thinking about your merchandise experience, how would you rate the Quality] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q94-A-3-Thinking about your merchandise experience, how would you rate the Value] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q94-A-4-Thinking about your merchandise experience, how would you rate the Efficiency of shopping / check-out] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q94-A-5-Thinking about your merchandise experience, how would you rate the OVERALL merchandise experience] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q95-Did you see or experience a great moment with one of our staff] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
)
GO
