CREATE TABLE [etl].[azure_customtable]
(
[ID] [int] NULL,
[Dimcustomerid] [int] NULL,
[SourceDB] [varchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SourceSystem] [varchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SSID] [varchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AccountID] [varchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CustomfieldBit1] [bit] NULL,
[CustomfieldBit2] [bit] NULL,
[CustomfieldBit3] [bit] NULL,
[CustomfieldBit4] [bit] NULL,
[CustomfieldBit5] [bit] NULL,
[CustomfieldBit6] [bit] NULL,
[CustomfieldBit7] [bit] NULL,
[CustomfieldBit8] [bit] NULL,
[CustomfieldBit9] [bit] NULL,
[CustomfieldBit10] [bit] NULL,
[CustomfieldNvarchar1] [nvarchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CustomfieldNvarchar2] [nvarchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CustomfieldNvarchar3] [nvarchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CustomfieldNvarchar4] [nvarchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CustomfieldNvarchar5] [nvarchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CustomfieldNvarchar6] [nvarchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CustomfieldNvarchar7] [nvarchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CustomfieldNvarchar8] [nvarchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CustomfieldNvarchar9] [nvarchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CustomfieldNvarchar10] [nvarchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CustomfieldNvarcharMAX1] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CustomfieldNvarcharMAX2] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CustomfieldNvarcharMAX3] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CustomfieldNvarcharMAX4] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CustomfieldNvarcharMAX5] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CustomFieldInt1] [int] NULL,
[CustomFieldInt2] [int] NULL,
[CustomFieldInt3] [int] NULL,
[CustomFieldInt4] [int] NULL,
[CustomFieldInt5] [int] NULL,
[CustomFieldInt6] [int] NULL,
[CustomFieldInt7] [int] NULL,
[CustomFieldInt8] [int] NULL,
[CustomFieldInt9] [int] NULL,
[CustomFieldInt10] [int] NULL,
[CustomFieldDecimal1] [numeric] (18, 8) NULL,
[CustomFieldDecimal2] [numeric] (18, 8) NULL,
[CustomFieldDecimal3] [numeric] (18, 8) NULL,
[CustomFieldDecimal4] [numeric] (18, 8) NULL,
[CustomFieldDecimal5] [numeric] (18, 8) NULL,
[CreatedDate] [datetime] NULL,
[CreatedBy] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[UpdatedDate] [datetime] NULL,
[UpdatedBy] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CustomfieldBit12] [bit] NULL,
[CustomfieldBit13] [bit] NULL,
[CustomfieldBit14] [bit] NULL,
[CustomfieldBit15] [bit] NULL,
[CustomfieldBit16] [bit] NULL,
[CustomfieldBit17] [bit] NULL,
[CustomfieldBit18] [bit] NULL,
[CustomfieldBit19] [bit] NULL,
[CustomfieldBit20] [bit] NULL,
[CustomfieldBit21] [bit] NULL,
[CustomfieldBit22] [bit] NULL,
[CustomfieldBit23] [bit] NULL,
[CustomfieldBit24] [bit] NULL,
[CustomfieldBit25] [bit] NULL,
[CustomfieldBit26] [bit] NULL,
[CustomFieldBit11] [bit] NULL,
[CustomFieldDateTime1] [datetime2] NULL,
[CustomFieldDateTime2] [datetime2] NULL,
[CustomFieldDateTime3] [datetime2] NULL,
[CustomFieldDateTime4] [datetime2] NULL,
[CustomFieldDateTime5] [datetime2] NULL
)
GO
