CREATE TABLE [mdm].[tmp_Contactmatch_data]
(
[DimCustomerId] [int] NULL,
[SSID] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SourceSystem] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ContactGUID] [uniqueidentifier] NULL,
[EmailPrimary] [nvarchar] (256) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FirstName] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LastName] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Suffix] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[customer_matchkey] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FuzzyNameGUID] [uniqueidentifier] NULL,
[AddressPrimaryCity] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AddressPrimaryStreet] [nvarchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AddressPrimaryZip] [nvarchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PhonePrimary] [nvarchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AddressPrimarySuite] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ExtAttribute6] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AccountId] [int] NULL,
[hashplaintext_1] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[hash_1] [varbinary] (32) NULL,
[hashplaintext_2] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[hash_2] [varbinary] (32) NULL,
[hashplaintext_3] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[hash_3] [varbinary] (32) NULL,
[hashplaintext_9] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[hash_9] [varbinary] (32) NULL,
[hashplaintext_10] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[hash_10] [varbinary] (32) NULL,
[hashplaintext_11] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[hash_11] [varbinary] (32) NULL,
[hashplaintext_12] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[hash_12] [varbinary] (32) NULL,
[hashplaintext_13] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[hash_13] [varbinary] (32) NULL,
[hashplaintext_14] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[hash_14] [varbinary] (32) NULL,
[hashplaintext_15] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[hash_15] [varbinary] (32) NULL,
[hashplaintext_16] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[hash_16] [varbinary] (32) NULL
)
GO
