CREATE TABLE [ods].[IMC_Optins_20180730]
(
[RECIPIENT_ID] [bigint] NULL,
[Email] [varchar] (147) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Opt In Date] [datetime] NULL,
[Opted Out] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Opt In Details] [varchar] (216) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Opted Out Date] [datetime] NULL,
[Opt Out Details] [varchar] (87) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Last Modified Date] [datetime] NULL,
[2017_Falcons_STM_Paid] [varchar] (12) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[2017_United_STM_Paid] [varchar] (12) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[2018_United_STM_Paid] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Duplicate] [varchar] (9) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Falcons_SingleGameBuyer_SSB] [varchar] (12) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Gameday1] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Gameday10] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Gameday2] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Gameday3] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Gameday4] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Gameday5] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Gameday7] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Gameday8] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Gameday9] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Matchday1] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Matchday10] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Matchday12] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Matchday13] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Matchday14] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Matchday15] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Matchday16] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Matchday17] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Matchday18] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Matchday2] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Matchday3] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Matchday4] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Matchday5] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Matchday6] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Matchday7] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Matchday8] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Matchday9] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PSL Owner] [varchar] (9) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PSL_Owner_SSB] [varchar] (12) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[United_MultiPack_SSB] [varchar] (12) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[United_SingleGameBuyer_SSB] [varchar] (12) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[optin_AF] [varchar] (9) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[optin_AF_date] [datetime] NULL,
[optin_AF_source] [varchar] (45) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[optin_AU] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[optin_AU_date] [datetime] NULL,
[optin_AU_source] [varchar] (45) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[optin_Stadium] [varchar] (9) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[optin_Stadium_date] [datetime] NULL,
[optin_Stadium_source] [varchar] (48) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[optout_AF_date] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[optout_AU_date] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[optout_Stadium_date] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
)
GO
