CREATE TABLE [ods].[IMC_SourceData_20170906]
(
[Opt In Details] [nvarchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Email Type] [nvarchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CRM Account ID] [nvarchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CRM Enable Sync] [nvarchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Opted Out Date] [nvarchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CRM Sync ID] [nvarchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EMAIL] [nvarchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CRM Lead Source] [nvarchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Last Modified Date] [nvarchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Opt Out Details] [nvarchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CRM Contact Type] [nvarchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Opt In Date] [nvarchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CREATED_FROM] [nvarchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[21 or older] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Academy Team] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Academy Tried Out] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Address1_City] [nvarchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Address1_Country] [nvarchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Address1_County] [nvarchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Address1_Line1] [nvarchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Address1_Line2] [nvarchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Address1_Line3] [nvarchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Address1_PostalCode] [nvarchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Address1_StateOrProvince] [nvarchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AF Season Schedule] [nvarchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Agree Official Rules] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AllowSMS] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Appointment Time] [nvarchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AssistantName] [nvarchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AssistantPhone] [nvarchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AUExclusiveContentNotifications] [int] NULL,
[AUInTheStadiumNotifications] [int] NULL,
[AUMatchStartNotifications] [int] NULL,
[AUParkingAndTransitNotifications] [int] NULL,
[AUScoringNotifications] [int] NULL,
[AUTeamNewsNotifications] [int] NULL,
[BirthDate] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cdi_facebook] [nvarchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cdi_linkedin] [nvarchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cdi_twitter] [nvarchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_ambffsuppression] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_BWContactId] [nvarchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Company] [nvarchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Corporate Entertainment] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CRM_Contact_ID] [nvarchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Current Stadium Employee] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DoNotBulkEMail] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DoNotBulkPostalMail] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DoNotEMail] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DoNotPostalMail] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Falcons Group] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Falcons Home Opponents] [nvarchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Falcons Insider] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Falcons Season Ticket Holder] [nvarchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Falcons Season Tix Due] [nvarchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Falcons Seating Preference] [nvarchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Falcons SGB TE TF] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FirstName] [nvarchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Founding Members no seats] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Founding Members with seats] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FullName] [nvarchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[GA Dome Premium Events] [nvarchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[GA Dome Seating Preferences] [nvarchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[GenderCode] [nvarchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Group Size] [nvarchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Group Type] [nvarchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[HasChildrenCode] [int] NULL,
[JobTitle] [nvarchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[KIA Account] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[kore_accountaliasidName] [nvarchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[kore_address1milesfromfacility] [decimal] (18, 0) NULL,
[kore_BWBaseDate] [nvarchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[kore_BWCompanyId] [nvarchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[kore_BWContactId] [nvarchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[kore_BWSequence] [int] NULL,
[kore_CheckedOutById] [nvarchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[kore_CheckedOutByIdName] [nvarchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[kore_InvoiceBalance] [money] NULL,
[kore_PrimaryAccountNumber] [nvarchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[kore_SinceDate] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[KORE_Type] [int] NULL,
[Last_Click] [varchar] (24) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Last_Open] [varchar] (24) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Last_Sent] [varchar] (24) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LastName] [nvarchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MBS Hiring Emails] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MiddleName] [nvarchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Mobile User Id] [nvarchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MobilePhone] [nvarchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[My Finder] [nvarchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[new_Address1_MetroArea] [nvarchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[new_AFYFNetwork] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[new_AMBFFNewsletter] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[new_AMBFFTrustees] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[new_AmericanExplorers] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[new_AtlantaFalconsNationalFootballLeague] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[new_AtlantaUnitedFCEventsFanPerksa] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[new_AtlantaUnitedFCMajorLeagueSoccer] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[new_BrokerFlag] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[new_FalconsNASSurveyLink] [nvarchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[new_FanCouncilURL] [nvarchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[new_FoundationSubscription] [nvarchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[new_HasKidsunder18] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[new_MLSFoundersSurveyLink] [nvarchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[new_MLSLiveCode] [nvarchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[new_new_subscription_MLSOfficialGearMail] [nvarchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[new_NFLAccount] [nvarchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[new_NFLAccountPassword] [nvarchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[new_NFLMC1] [nvarchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[new_NFLMCCode1] [nvarchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[new_NFLMCCode2] [nvarchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[new_NFLMCCode3] [nvarchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[new_NFLMCCode4] [nvarchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[new_NFLMCURL2] [nvarchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[new_NSCheckedOutBy] [nvarchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[new_NSCheckedOutByName] [nvarchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[new_NSLicenseeName] [nvarchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[new_RelocationDateTime] [nvarchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[new_SponsorshipCheckedOutBy] [nvarchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[new_SponsorshipCheckedOutByName] [nvarchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[new_Subscription_MLSSubscription] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[new_Subscription_PreferredPartner] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[new_Subscription_Ticket_Offers] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[new_subscriptionNewStadiumInformationOffers] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[new_UnitedCheckedOutBy] [nvarchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[new_UnitedCheckedOutByName] [nvarchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[new_VirtualseatView] [nvarchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[new_WNPFNetwork] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Opt Out of Arthur M Blank Foundation Email Communication] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Opt Out of Atlanta Falcons Email Communication] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Opt Out of Atlanta United Email Communication] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Part Time Positions] [nvarchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Phone Call Opt In] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Playoff Payment] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Preferred Partner] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Preferred Ticket Price] [nvarchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PreferredLanguage] [nvarchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Primary Rep] [nvarchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Primary Rep Email] [nvarchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Primary Rep Name] [nvarchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Primary Rep Phone] [nvarchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PSL Owner] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Question or Comment] [nvarchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Salutation] [nvarchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Seating Level Preference] [nvarchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Send Hour] [nvarchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[StateCode] [nvarchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Suffix] [nvarchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Team Member Referral] [nvarchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Team Member Requirements] [nvarchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Telephone1] [nvarchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Telephone2] [nvarchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[United Season Ticket Holder] [nvarchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[United Seating Preference] [nvarchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[UnitedStayConnected] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[UTD Acct Number] [nvarchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[UTD Event Sign Up] [nvarchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[UTD Group] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[UTD Multi Game] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[UTD Season Schedule] [nvarchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[UTD Season Tix Due] [money] NULL,
[UTD SGB TE TF] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[UTD Test_Behavior] [nvarchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[UTD Test_Rank] [nvarchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[UTD Test_Score] [nvarchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MOBILE_USER_ID] [nvarchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MBS Seating Interest] [nvarchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[IsPrimary] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ETL__CreatedDate] [datetime] NULL,
[ETL__UpdatedDate] [datetime] NULL,
[PSL_Owner_SSB] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[2017_United_STM_Paid] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[United_MultiPack_SSB] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[United_SingleGameBuyer_SSB] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[2017_Falcons_STM_Paid] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Falcons_SingleGameBuyer_SSB] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
)
GO
