CREATE TABLE [ProdCopy].[AccountExtensionBase]
(
[ETL_ID] [int] NOT NULL IDENTITY(1, 1),
[ETL_CreatedDate] [datetime] NOT NULL CONSTRAINT [DF__AccountEx__ETL_C__6C8E1007] DEFAULT (getdate()),
[ETL_UpdatedDate] [datetime] NOT NULL CONSTRAINT [DF__AccountEx__ETL_U__6D823440] DEFAULT (getdate()),
[ETL_IsDeleted] [bit] NOT NULL CONSTRAINT [DF__AccountEx__ETL_I__6E765879] DEFAULT ((0)),
[ETL_DeletedDate] [datetime] NULL,
[ETL_DeltaHashKey] [binary] (32) NULL,
[AccountId] [uniqueidentifier] NOT NULL,
[KORE_address1_telephone1dncstatus] [bit] NULL,
[KORE_address1_telephone2dncstatus] [bit] NULL,
[KORE_address1_telephone3dncstatus] [bit] NULL,
[KORE_address2_telephone1dncstatus] [bit] NULL,
[KORE_address2_telephone2dncstatus] [bit] NULL,
[KORE_address2_telephone3dncstatus] [bit] NULL,
[KORE_LastContacted] [datetime] NULL,
[KORE_lastcontactedactivityid] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[KORE_LastSync] [datetime] NULL,
[KORE_LegalName] [nvarchar] (300) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[KORE_NextContact] [datetime] NULL,
[KORE_nextcontactactivityid] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[kore_StrippedName] [nvarchar] (160) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[KORE_telephone1dncstatus] [bit] NULL,
[KORE_telephone2dncstatus] [bit] NULL,
[KORE_telephone3dncstatus] [bit] NULL,
[KORE_Type] [int] NULL,
[kore_billingcontactid] [uniqueidentifier] NULL,
[kore_countryid] [uniqueidentifier] NULL,
[kore_stateorprovinceid] [uniqueidentifier] NULL,
[kore_sourcemarketinglistid] [uniqueidentifier] NULL,
[kore_coordinatorid] [uniqueidentifier] NULL,
[kore_CreatedByAccountAlias] [bit] NULL,
[kore_CurrentlyBeingWorked] [bit] NULL,
[kore_HasCheckedOutContact] [bit] NULL,
[kore_BusinessWiseID] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[kore_BWBuildingType] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[kore_BWEmployeesAtAllSites] [int] NULL,
[kore_BWEmployeesAtSite] [int] NULL,
[kore_BWEstimatedSales] [int] NULL,
[kore_BWExactSize] [int] NULL,
[kore_BWInternationalBusiness] [bit] NULL,
[kore_BWOwnBuilding] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[kore_BWSector] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[kore_BWSICDescription] [nvarchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[kore_BWSiteType] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[kore_BWStartYear] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[kore_BWTotalSites] [int] NULL,
[cdi_allowtextmessages] [bit] NULL,
[new_MetroArea] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[new_GeoGroup] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[new_ZipcodeId] [uniqueidentifier] NULL,
[new_ExternalCoordinator] [uniqueidentifier] NULL,
[kore_industryid] [uniqueidentifier] NULL,
[new_SponsorshipRep] [uniqueidentifier] NULL,
[kore_ExternalAccountID] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[li_CompanyId] [int] NULL,
[kore_TaxExemptStatus] [bit] NULL,
[KORE_Agency] [int] NULL,
[KORE_AuthorizedSignor] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[kore_Headquarters] [nvarchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[KORE_SponsorAccountNumber] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[KORE_StateofIncorporation] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[kore_USOffice] [nvarchar] (400) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[KORE_AgencyId] [uniqueidentifier] NULL,
[kore_authorizedsignorid] [uniqueidentifier] NULL,
[kore_externalreportingpartnerid] [uniqueidentifier] NULL,
[kore_NBACategoryId] [uniqueidentifier] NULL,
[kore_NBASponsorId] [uniqueidentifier] NULL,
[KORE_StateofIncorporationId] [uniqueidentifier] NULL,
[kore_salespersonid] [uniqueidentifier] NULL,
[client_gpaccountnumber] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_GPCustomerClass] [int] NULL,
[client_syncedwithgp] [bit] NULL,
[client_triggergp] [bit] NULL
)
GO
ALTER TABLE [ProdCopy].[AccountExtensionBase] ADD CONSTRAINT [PK__AccountE__349DA5A6D29BB858] PRIMARY KEY CLUSTERED  ([AccountId])
GO
