CREATE TABLE [ProdCopystg].[ContactExtensionBase]
(
[ETL_ID] [int] NOT NULL IDENTITY(1, 1),
[ETL_CreatedDate] [datetime] NOT NULL CONSTRAINT [DF__ContactEx__ETL_C__009508B4] DEFAULT (getdate()),
[ETL_UpdatedDate] [datetime] NOT NULL CONSTRAINT [DF__ContactEx__ETL_U__01892CED] DEFAULT (getdate()),
[ETL_IsDeleted] [bit] NOT NULL CONSTRAINT [DF__ContactEx__ETL_I__027D5126] DEFAULT ((0)),
[ETL_DeletedDate] [datetime] NULL,
[ETL_DeltaHashKey] [binary] (32) NULL,
[ContactId] [uniqueidentifier] NULL,
[KORE_address1_telephone1dncstatus] [bit] NULL,
[KORE_address1_telephone2dncstatus] [bit] NULL,
[KORE_address1_telephone3dncstatus] [bit] NULL,
[kore_address1milesfromfacility] [numeric] (23, 10) NULL,
[KORE_address2_telephone1dncstatus] [bit] NULL,
[KORE_address2_telephone2dncstatus] [bit] NULL,
[KORE_address2_telephone3dncstatus] [bit] NULL,
[KORE_assistantphonedncstatus] [bit] NULL,
[KORE_AttentionName] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[KORE_ImportID] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[KORE_LastContacted] [datetime] NULL,
[KORE_LastSync] [datetime] NULL,
[KORE_ListAttributeName] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[KORE_ListAttributeValue] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[KORE_managerphonedncstatus] [bit] NULL,
[KORE_mobilephonedncstatus] [bit] NULL,
[KORE_SeniorityDate] [datetime] NULL,
[KORE_telephone1DNCStatus] [bit] NULL,
[KORE_telephone1dncstatustype] [int] NULL,
[KORE_telephone2dncstatus] [bit] NULL,
[KORE_telephone2dncstatustype] [int] NULL,
[KORE_telephone3dncstatus] [bit] NULL,
[KORE_telephone3dncstatustype] [int] NULL,
[KORE_Type] [int] NULL,
[kore_countryid] [uniqueidentifier] NULL,
[kore_stateorprovinceid] [uniqueidentifier] NULL,
[kore_sourcemarketinglistid] [uniqueidentifier] NULL,
[kore_lastcontactedbyid] [uniqueidentifier] NULL,
[kore_AccountNumbers] [nvarchar] (300) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[kore_CheckedOutUntil] [datetime] NULL,
[kore_CompanyName] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[kore_OptOutOfDuplicateDetection] [bit] NULL,
[kore_ParentCustomerIdStrippedName] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[kore_PrimaryAccountNumber] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[kore_TicketingContactType] [int] NULL,
[kore_accountaliasid] [uniqueidentifier] NULL,
[kore_CheckedOutById] [uniqueidentifier] NULL,
[client_BWContactId] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[kore_BWBaseDate] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[kore_BWCompanyId] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[kore_BWContactId] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[kore_BWSequence] [int] NULL,
[cdi_age] [int] NULL,
[cdi_allowtextmessages] [bit] NULL,
[cdi_facebook] [nvarchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cdi_gender] [bit] NULL,
[cdi_grade] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cdi_identifiedon] [datetime] NULL,
[cdi_image] [nvarchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cdi_ip] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cdi_latitude] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cdi_linkedin] [nvarchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cdi_Longitude] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cdi_partitionkey] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cdi_rowkey] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cdi_score] [int] NULL,
[cdi_social] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cdi_totalscore] [int] NULL,
[cdi_twitter] [nvarchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cdi_visitorkey] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[new_DomeAccountNumber] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[new_DomeContractStart] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[new_DomeContractEnd] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[new_DomeContractExt] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[new_DomeContractEscalator] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[new_DomeSeats] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[new_somethingelse] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[new_ImportSource] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[new_MyFinder] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[new_GeorgiaDomeSeats] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[new_Source] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[new_Subscription_EReport] [bit] NULL,
[new_Subscription_Postgame_STH] [bit] NULL,
[new_Subscription_Pregame_STH] [bit] NULL,
[new_Subscription_GearMail] [bit] NULL,
[new_Subscription_TicketSuiteSales] [bit] NULL,
[new_Subscription_PreferredPartner] [bit] NULL,
[new_Subscription_Ticket_Offers] [bit] NULL,
[kore_InvoiceBalance] [money] NULL,
[kore_invoicebalance_Base] [money] NULL,
[kore_SinceDate] [datetime] NULL,
[new_PIF_Amount] [money] NULL,
[new_pif_amount_Base] [money] NULL,
[new_5MonthlyPaymentAmt] [money] NULL,
[new_5monthlypaymentamt_Base] [money] NULL,
[new_40_60PaymentAmt] [money] NULL,
[new_40_60paymentamt_Base] [money] NULL,
[new_PersonalURL] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[new_FavoritePlayer] [int] NULL,
[new_RelocationDateTime] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[new_NFLAccount] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[new_NFLAccountPassword] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[new_CurrentSeasonAccountHolder] [bit] NULL,
[new_Subscription_MLSSubscription] [bit] NULL,
[new_new_subscription_MLSOfficialGearMail] [bit] NULL,
[new_Address1_MetroArea] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[new_NFLMC1] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[new_NFLMCCode1] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[new_NFLMCURL2] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[new_NFLMCCode2] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[new_NFLMCCode3] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[new_NFLMCCode4] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[new_CurrentSpend] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[new_NSWaitlistConfirmed] [bit] NULL,
[kore_archticsids] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[kore_ExternalContactId] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[kore_GroupBuyer] [bit] NULL,
[kore_GroupCategory] [int] NULL,
[kore_HeritageNationality] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[kore_MilesFromFacility] [numeric] (23, 10) NULL,
[kore_MiniPlanHolder] [bit] NULL,
[kore_OverrideCheckoutExpiration] [bit] NULL,
[kore_PrimaryArchticsId] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[kore_SeasonTicketHolder] [bit] NULL,
[kore_SecondaryArchticsName] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[kore_SecondaryEmail] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[kore_SuiteBuyer] [bit] NULL,
[kore_GroupSalesRep] [uniqueidentifier] NULL,
[kore_SuiteSalesRep] [uniqueidentifier] NULL,
[kore_TicketingSalesRep] [uniqueidentifier] NULL,
[kore_TicketingServiceRep] [uniqueidentifier] NULL,
[li_CompanyId] [int] NULL,
[li_MemberToken] [nvarchar] (80) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[new_SponsorshipCheckedOutBy] [uniqueidentifier] NULL,
[new_SponsorshipCheckedOutUntil] [datetime] NULL,
[new_NSCheckedOutBy] [uniqueidentifier] NULL,
[new_NSCheckedOutUntil] [datetime] NULL,
[new_AMBFFNewsletter] [bit] NULL,
[new_AFYFNetwork] [bit] NULL,
[new_WNPFNetwork] [bit] NULL,
[new_AmericanExplorers] [bit] NULL,
[new_AMBFFTrustees] [bit] NULL,
[KORE_IsBillingContact] [bit] NULL,
[KORE_IsPrimaryContact] [bit] NULL,
[KORE_sponsoraccountnumber] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[new_NSReservationDate] [datetime] NULL,
[client_gpaccountnumber] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_GPCustomerClass] [int] NULL,
[client_triggergp] [bit] NULL,
[new_NSAppointmentIdentifier] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[new_NSPURL] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[new_NSPasscode] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[new_NSRepEmail] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[new_NSRepPhone] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[new_MLSFoundersSurveyLink] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[new_NSLicenseeName] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[new_FoundationSubscription] [uniqueidentifier] NULL,
[new_FuturePhaseRep] [uniqueidentifier] NULL,
[new_FuturePhaseNotes] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[new_subscriptionNewStadiumInformationOffers] [bit] NULL,
[new_AllocatedSeatLocation] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[new_VirtualseatView] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[new_MLSLiveCode] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[new_NSReserveSeatInterest] [int] NULL,
[new_NSClubSeatInterest] [int] NULL,
[new_NSReserveInterest] [bit] NULL,
[new_NSClubInterest] [bit] NULL,
[new_NSSuiteInterest] [bit] NULL,
[new_BrokerFlag] [bit] NULL,
[new_FalconsNASSurveyLink] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[new_TypeOfGroup] [int] NULL,
[new_MiscField] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[new_InterestType] [int] NULL,
[new_NumberofSeats] [int] NULL,
[new_InterestLevel] [int] NULL,
[new_SeatingPreference] [int] NULL,
[new_NumberofTickets] [int] NULL,
[new_AtlantaUnitedFCMajorLeagueSoccer] [bit] NULL,
[new_AtlantaUnitedFCEventsFanPerksa] [bit] NULL,
[new_AtlantaFalconsNationalFootballLeague] [bit] NULL,
[new_FanCouncilURL] [nvarchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[new_MemoriesStartingCredits] [int] NULL,
[new_MemoriesRedeemedCredits] [int] NULL,
[new_MemoriesRemainingCredits] [int] NULL,
[new_MemoriesLastUpdated] [datetime] NULL,
[new_MemoriesRegisteredMember] [bit] NULL,
[new_PSLAcctMgrPIN] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[new_TETicketsPurchased] [int] NULL,
[new_TEGamesPurchased] [int] NULL,
[new_TEMoneySpent] [money] NULL,
[new_temoneyspent_Base] [money] NULL,
[new_ExcludeFromMBSEmails] [int] NULL,
[new_SGBGamesPurchased] [int] NULL,
[new_SGBTicketsPurchased] [int] NULL,
[new_SGBMoneySpent] [money] NULL,
[new_sgbmoneyspent_Base] [money] NULL,
[new_ATLUTDSeasonTickets] [bit] NULL,
[new_ATLUTDGroupTickets] [bit] NULL,
[new_ATLUTDSingleGameTickets] [bit] NULL,
[new_TopContact] [int] NULL
)
GO
ALTER TABLE [ProdCopystg].[ContactExtensionBase] ADD CONSTRAINT [PK__ContactE__7EF6BFCD53393210] PRIMARY KEY CLUSTERED  ([ETL_ID])
GO
