CREATE TABLE [rpt].[MV_FactTicketSales_Falcons_HM]
(
[DimSeatId] [int] NOT NULL,
[SeatKey] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DefaultPriceCode] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PriceCodeDescription] [varchar] (22) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[saledate] [date] NULL,
[accountid] [int] NULL,
[PlanCode] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SectionName] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RowName] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[seat] [int] NULL,
[pc1] [nvarchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[pc2] [nvarchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[pc3] [nvarchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[pc4] [nvarchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[isavailable] [bit] NULL,
[issold] [bit] NULL,
[iscomp] [bit] NULL,
[TotalRevenue] [decimal] (38, 6) NULL,
[QtyFSE] [int] NULL,
[TotalPaidAmount] [decimal] (38, 20) NULL,
[TotalOwedAmount] [decimal] (38, 20) NULL,
[HeldDimPriceCodeId] [int] NULL,
[HeldDimClassTMId] [int] NULL,
[HeldSeatValue] [decimal] (18, 6) NULL,
[IsReserved] [bit] NULL,
[usr] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[invoice_id] [bigint] NULL,
[hours_held] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[plan_datetime] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[invoice_date] [datetime] NULL,
[sell_location_code] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[sell_location_name] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
)
GO
