CREATE TABLE [src].[TurnKey_GetSurveyInformation]
(
[SK] [bigint] NULL,
[ETL__multi_query_value_for_audit] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[L1_AllData_xmlns] [nvarchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[L2_AllData_Question_heading] [nvarchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[L2_AllData_Question_class] [nvarchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[L2_AllData_Question_column] [nvarchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[L3_AllData_Question_heading] [nvarchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[L3_AllData_Question_class] [nvarchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[L3_AllData_Question_column] [nvarchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[L3_AllData_Question_Option_id] [nvarchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[L3_AllData_Question_Option_column] [nvarchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[L3_AllData_Question_Option_type] [nvarchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[L3_AllData_Question_Side_id] [nvarchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[L3_AllData_Question_Side_class] [nvarchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[L4_AllData_Question_Side_id] [nvarchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[L4_AllData_Question_Side_class] [nvarchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[L4_AllData_Question_Option_id] [nvarchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[L4_AllData_Question_Option_column] [nvarchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[L4_AllData_Question_Option_type] [nvarchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[L4_AllData_Question_Choice_id] [nvarchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[L4_AllData_Question_Choice_specify] [nvarchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[L4_AllData_Question_Name_column] [nvarchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[L4_AllData_Question_Name_type] [nvarchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[L4_AllData_Question_Tags_column] [nvarchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[L4_AllData_Question_Tags_type] [nvarchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[L4_AllData_Question_Latitude_column] [nvarchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[L4_AllData_Question_Latitude_type] [nvarchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[L4_AllData_Question_Longitude_column] [nvarchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[L4_AllData_Question_Longitude_type] [nvarchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[L4_AllData_Question_Rating_column] [nvarchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[L4_AllData_Question_Rating_type] [nvarchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[L4_AllData_Question_Choice_column] [nvarchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[L5_AllData_Question_Option_id] [nvarchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[L5_AllData_Question_Option_column] [nvarchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[L5_AllData_Question_Option_type] [nvarchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[L5_AllData_Question_Choice_id] [nvarchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[L5_AllData_Question_Choice_column] [nvarchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[L5_AllData_Question_Choice_specify] [nvarchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[L5_AllData_Question_Side_id] [nvarchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[L5_AllData_Question_Side_class] [nvarchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[L5_AllData_Question_Side_Topic_id] [nvarchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[L5_AllData_Question_Side_Topic_column] [nvarchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[L6_AllData_Question_Side_Topic_id] [nvarchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[L6_AllData_Question_Side_Topic_column] [nvarchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[L7_AllData_Question_Side_Topic_id] [nvarchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[L7_AllData_Question_Side_Topic_column] [nvarchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[L8_AllData_Question_Side_Topic_Choice_id] [nvarchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[L8_AllData_Question_Side_Topic_Choice_column] [nvarchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
)
GO
