CREATE TABLE [SSBCLOUD\cwork].[OLE DB Destination]
(
[ETL__ID] [int] NOT NULL IDENTITY(1, 1),
[Email] [varchar] (996) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Opt In Date] [varchar] (126) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Opted Out] [varchar] (18) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Opt In Details] [varchar] (444) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Email Type] [varchar] (48) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Opted Out Date] [varchar] (126) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Opt Out Details] [varchar] (276) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CRM Sync ID] [varchar] (228) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CRM Enable Sync] [varchar] (96) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CRM Contact Type] [varchar] (96) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CRM Account ID] [varchar] (12) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[2016 PSL Payment Paid] [varchar] (36) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[2017 PSL Amount Due] [varchar] (60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[2017 PSL Payment Paid] [varchar] (36) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[21 or older] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AF Season Schedule] [varchar] (12) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AF Ticket Offers] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AUExclusiveContentNotifications] [varchar] (12) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AUInTheStadiumNotifications] [varchar] (12) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AUMatchStartNotifications] [varchar] (18) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AUParkingAndTransitNotifications] [varchar] (12) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AUScoringNotifications] [varchar] (18) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AUTeamNewsNotifications] [varchar] (12) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Academy Team] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Academy Tried Out] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Additional Comments] [varchar] (12) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Address1_City] [varchar] (186) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Address1_Country] [varchar] (132) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Address1_County] [varchar] (90) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Address1_Line1] [varchar] (264) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Address1_Line2] [varchar] (252) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Address1_Line3] [varchar] (192) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Address1_PostalCode] [varchar] (174) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Address1_StateOrProvince] [varchar] (198) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Agree Official Rules] [varchar] (120) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AllowSMS] [varchar] (60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Appointment Time] [varchar] (48) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AssistantName] [varchar] (228) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AssistantPhone] [varchar] (102) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Associated Archtics ID Suite Owner Admin] [varchar] (36) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BirthDate] [varchar] (72) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CRM_Contact_ID] [varchar] (228) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Company] [varchar] (246) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Corporate Client or Employee Entertainment] [varchar] (228) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Corporate Entertainment] [varchar] (228) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Current Stadium Employee] [varchar] (228) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DoNotBulkEMail] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DoNotBulkPostalMail] [varchar] (114) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DoNotEMail] [varchar] (24) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DoNotPostalMail] [varchar] (24) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Executive Member] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Falcons Group] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Falcons Home Opponents] [varchar] (2082) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Falcons Insider] [varchar] (324) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Falcons SGB TE TF] [varchar] (570) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Falcons Season Ticket Holder] [varchar] (576) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Falcons Season Tix Due] [varchar] (72) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Falcons Seating Preference] [varchar] (792) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FirstName] [varchar] (312) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Founding Members no seats] [varchar] (96) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Founding Members with seats] [varchar] (90) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FullName] [varchar] (378) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[GA Dome Premium Events] [varchar] (258) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[GA Dome Seating Preferences] [varchar] (792) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[GenderCode] [varchar] (312) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Group Size] [varchar] (120) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Group Type] [varchar] (108) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[HasChildrenCode] [varchar] (90) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[JobTitle] [varchar] (258) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[KIA Account] [varchar] (174) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[KORE_Type] [varchar] (168) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LastName] [varchar] (432) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Last_Click] [varchar] (258) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Last_Open] [varchar] (300) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Last_Sent] [varchar] (126) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MBS Hiring Emails] [varchar] (168) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MBS Seating Interest] [varchar] (372) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MiddleName] [varchar] (258) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Mobile User Id] [varchar] (180) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MobilePhone] [varchar] (180) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[My Finder] [varchar] (198) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Opt Out of Arthur M Blank Foundation Email Communication] [varchar] (198) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Opt Out of Atlanta Falcons Email Communication] [varchar] (198) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Opt Out of Atlanta United Email Communication] [varchar] (96) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PSL Owner] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Part Time Positions] [varchar] (498) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Phone Call Opt In] [varchar] (54) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Playoff Payment] [varchar] (228) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Preferred Partner] [varchar] (348) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Preferred Ticket Price] [varchar] (102) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PreferredLanguage] [varchar] (54) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Primary Rep] [varchar] (54) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Primary Rep Email] [varchar] (24) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Primary Rep Name] [varchar] (12) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Primary Rep Phone] [varchar] (12) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Question or Comment] [varchar] (984) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Salutation] [varchar] (906) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Seating Level Preference] [varchar] (198) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Send Hour] [varchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[StateCode] [varchar] (102) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Suffix] [varchar] (90) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Team Member Referral] [varchar] (264) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Team Member Requirements] [varchar] (228) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Telephone1] [varchar] (168) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Telephone2] [varchar] (138) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[UTD Acct Number] [varchar] (126) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[UTD Event Sign Up] [varchar] (354) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[UTD Group] [varchar] (96) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[UTD Group  Type] [varchar] (96) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[UTD Group Size] [varchar] (12) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[UTD Home Opponents] [varchar] (12) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[UTD Multi Game] [varchar] (96) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[UTD SGB TE TF] [varchar] (36) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[UTD Season Schedule] [varchar] (12) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[UTD Season Tix Due] [varchar] (18) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[UTD Seating Preferences] [varchar] (18) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[UTD Test_Behavior] [varchar] (18) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[UTD Test_Rank] [varchar] (18) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[UTD Test_Score] [varchar] (18) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[United Season Ticket Holder] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[United Seating Preference] [varchar] (738) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[UnitedStayConnected] [varchar] (684) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Unsubscribe from CD] [varchar] (180) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cdi_facebook] [varchar] (282) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cdi_linkedin] [varchar] (324) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cdi_twitter] [varchar] (204) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_BWContactId] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_ambffsuppression] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[kore_BWBaseDate] [varchar] (24) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[kore_BWCompanyId] [varchar] (210) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[kore_BWContactId] [varchar] (102) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[kore_BWSequence] [varchar] (24) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[kore_CheckedOutById] [varchar] (228) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[kore_CheckedOutByIdName] [varchar] (228) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[kore_InvoiceBalance] [varchar] (228) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[kore_PrimaryAccountNumber] [varchar] (228) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[kore_SinceDate] [varchar] (84) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[kore_accountaliasidName] [varchar] (348) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[kore_address1milesfromfacility] [varchar] (252) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[new_AFYFNetwork] [varchar] (192) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[new_AMBFFNewsletter] [varchar] (132) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[new_AMBFFTrustees] [varchar] (96) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[new_Address1_MetroArea] [varchar] (138) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[new_AmericanExplorers] [varchar] (138) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[new_AtlantaFalconsNationalFootballLeague] [varchar] (138) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[new_AtlantaUnitedFCEventsFanPerksa] [varchar] (54) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[new_AtlantaUnitedFCMajorLeagueSoccer] [varchar] (138) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[new_BrokerFlag] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[new_ExcludeFromMBSEmails] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[new_FalconsNASSurveyLink] [varchar] (660) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[new_FanCouncilURL] [varchar] (618) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[new_FoundationSubscription] [varchar] (618) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[new_HasKidsunder18] [varchar] (618) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[new_MLSFoundersSurveyLink] [varchar] (660) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[new_MLSLiveCode] [varchar] (654) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[new_MemoriesLastUpdated] [varchar] (66) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[new_MemoriesRedeemedCredits] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[new_MemoriesRegisteredMember] [varchar] (24) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[new_MemoriesRemainingCredits] [varchar] (24) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[new_MemoriesStartingCredits] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[new_NFLAccount] [varchar] (60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[new_NFLAccountPassword] [varchar] (60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[new_NFLMC1] [varchar] (546) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[new_NFLMCCode1] [varchar] (510) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[new_NFLMCCode2] [varchar] (126) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[new_NFLMCCode3] [varchar] (126) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[new_NFLMCCode4] [varchar] (84) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[new_NFLMCURL2] [varchar] (372) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[new_NSCheckedOutBy] [varchar] (372) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[new_NSCheckedOutByName] [varchar] (228) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[new_NSLicenseeName] [varchar] (228) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[new_RelocationDateTime] [varchar] (168) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[new_SponsorshipCheckedOutBy] [varchar] (228) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[new_SponsorshipCheckedOutByName] [varchar] (228) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[new_Subscription_EReport] [varchar] (90) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[new_Subscription_GearMail] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[new_Subscription_MLSSubscription] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[new_Subscription_Postgame_STH] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[new_Subscription_PreferredPartner] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[new_Subscription_Pregame_STH] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[new_Subscription_TicketSuiteSales] [varchar] (24) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[new_Subscription_Ticket_Offers] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[new_UnitedCheckedOutBy] [varchar] (228) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[new_UnitedCheckedOutByName] [varchar] (228) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[new_VirtualseatView] [varchar] (456) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[new_WNPFNetwork] [varchar] (108) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[new_new_subscription_MLSOfficialGearMail] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[new_subscriptionNewStadiumInformationOffers] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
)
GO
