CREATE TABLE [stg].[silverpop_exportlist_0_catchup]
(
[RECIPIENT_ID] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Email] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Opt In Date] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Opted Out] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Opt In Details] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Email Type] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Opted Out Date] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Opt Out Details] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CRM Sync ID] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CRM Enable Sync] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CRM Contact Type] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CRM Account ID] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[2016 PSL Payment Paid] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[2017 PSL Amount Due] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[2017 PSL Payment Paid] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[2017_Falcons_STM_Paid] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[2017_United_STM_Paid] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[2018_United_STM_Paid] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[21 or older] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AF Season Schedule] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AF Ticket Offers] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AFExclusiveContent] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AFInDome] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AFLocationServices] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AFMediaNotifications] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AFOffersPromotions] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AFParkingTransportation] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AFScoreUpdatebyQuarter] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AFScoringPlays] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AFTeamNews] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AUExclusiveContentNotifications] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AUInTheStadiumNotifications] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AUMatchStartNotifications] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AUOffersPromotions] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AUParkingAndTransitNotifications] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AUScoringNotifications] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AUTeamNewsNotifications] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Academy Team] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Academy Tried Out] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Additional Comments] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Address1_City] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Address1_Country] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Address1_County] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Address1_Line1] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Address1_Line2] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Address1_Line3] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Address1_PostalCode] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Address1_StateOrProvince] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Agree Official Rules] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AllowSMS] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Appointment Time] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AssistantName] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AssistantPhone] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Associated Archtics ID Suite Owner Admin] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AtlantaFalconsProspect] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AtlantaUnitedEnrolledInAutoRenewal] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BirthDate] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CRM Sync ID 2] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CRM_Contact_ID] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Company] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Corporate Client or Employee Entertainment] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Corporate Entertainment] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Current Stadium Employee] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DoNotBulkEMail] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DoNotBulkPostalMail] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DoNotEMail] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DoNotPostalMail] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Duplicate] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Executive Member] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Falcons Group] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Falcons Home Opponents] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Falcons Insider] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Falcons SGB TE TF] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Falcons Season Ticket Holder] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Falcons Season Tix Due] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Falcons Seating Preference] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Falcons_SingleGameBuyer_SSB] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FirstName] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Founding Members no seats] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Founding Members with seats] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FullName] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[GA Dome Premium Events] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[GA Dome Seating Preferences] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[GenderCode] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Group Size] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Group Type] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[HasChildrenCode] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[JobTitle] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[KIA Account] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[KORE_Type] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LastName] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Last_Click] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Last_Open] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Last_Sent] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MBS Concert Garth Brooks 20170619] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MBS Events] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MBS Events Stay Informed] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MBS Group Tour Type] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MBS Hiring Emails] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MBS Seating Interest] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MBS Tour Interest 20170628] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MiddleName] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Mobile User Id] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MobilePhone] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[My Finder] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Opt Out of Arthur M Blank Foundation Email Communication] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Opt Out of Atlanta Falcons Email Communication] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Opt Out of Atlanta United Email Communication] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PSL Owner] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PSL_Owner_SSB] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Part Time Positions] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Phone Call Opt In] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Playoff Payment] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Preferred Partner] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Preferred Ticket Price] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PreferredLanguage] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Primary Rep] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Primary Rep Email] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Primary Rep Name] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Primary Rep Phone] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Question or Comment] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Salutation] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Seating Level Preference] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Send Hour] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[StateCode] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Suffix] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Team Member Referral] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Team Member Requirements] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Telephone1] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Telephone2] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Test Opens for Email_Behavior] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Test Opens for Email_Rank] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Test Opens for Email_Score] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[UTD Acct Number] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[UTD Event Sign Up] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[UTD Group] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[UTD Group  Type] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[UTD Group Size] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[UTD Home Opponents] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[UTD Multi Game] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[UTD SGB TE TF] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[UTD Season Schedule] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[UTD Season Tix Due] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[UTD Seating Preferences] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[UTD Test_Behavior] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[UTD Test_Rank] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[UTD Test_Score] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[United Season Ticket Holder] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[United Seating Preference] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[UnitedStayConnected] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[United_MultiPack_SSB] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[United_SingleGameBuyer_SSB] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Unsubscribe from CD] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Web Form First Name] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Web Form Last Name] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Web Form Telephone1] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Web Form Zip Code] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cdi_facebook] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cdi_linkedin] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cdi_twitter] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_BWContactId] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_ambffsuppression] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[kore_BWBaseDate] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[kore_BWCompanyId] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[kore_BWContactId] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[kore_BWSequence] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[kore_CheckedOutById] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[kore_CheckedOutByIdName] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[kore_InvoiceBalance] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[kore_PrimaryAccountNumber] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[kore_SinceDate] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[kore_accountaliasidName] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[kore_address1milesfromfacility] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[new_AFYFNetwork] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[new_AMBFFNewsletter] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[new_AMBFFTrustees] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[new_Address1_MetroArea] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[new_AmericanExplorers] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[new_AtlantaFalconsNationalFootballLeague] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[new_AtlantaUnitedFCEventsFanPerksa] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[new_AtlantaUnitedFCMajorLeagueSoccer] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[new_BrokerFlag] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[new_ExcludeFromMBSEmails] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[new_FalconsNASSurveyLink] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[new_FanCouncilURL] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[new_FoundationSubscription] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[new_HasKidsunder18] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[new_MLSFoundersSurveyLink] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[new_MLSLiveCode] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[new_MemoriesLastUpdated] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[new_MemoriesRedeemedCredits] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[new_MemoriesRegisteredMember] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[new_MemoriesRemainingCredits] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[new_MemoriesStartingCredits] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[new_NFLAccount] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[new_NFLAccountPassword] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[new_NFLMC1] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[new_NFLMCCode1] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[new_NFLMCCode2] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[new_NFLMCCode3] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[new_NFLMCCode4] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[new_NFLMCURL2] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[new_NSCheckedOutBy] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[new_NSCheckedOutByName] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[new_NSLicenseeName] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[new_RelocationDateTime] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[new_SponsorshipCheckedOutBy] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[new_SponsorshipCheckedOutByName] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[new_Subscription_EReport] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[new_Subscription_GearMail] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[new_Subscription_MLSSubscription] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[new_Subscription_Postgame_STH] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[new_Subscription_PreferredPartner] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[new_Subscription_Pregame_STH] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[new_Subscription_TicketSuiteSales] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[new_Subscription_Ticket_Offers] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[new_UnitedCheckedOutBy] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[new_UnitedCheckedOutByName] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[new_VirtualseatView] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[new_WNPFNetwork] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[new_new_subscription_MLSOfficialGearMail] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[new_subscriptionNewStadiumInformationOffers] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
)
GO
