IF NOT EXISTS (SELECT * FROM master.dbo.syslogins WHERE loginname = N'SSBCLOUD\cwork')
CREATE LOGIN [SSBCLOUD\cwork] FROM WINDOWS
GO
CREATE USER [SSBCLOUD\cwork] FOR LOGIN [SSBCLOUD\cwork] WITH DEFAULT_SCHEMA=[SSBCLOUD\cwork]
GO
REVOKE CONNECT TO [SSBCLOUD\cwork]
